// A structure goes by the global holding it that comes first in the
// identifier table: a new global takes the lowest slot a deleted one freed,
// else the next. Assignments to locals name nothing (#55).
C := ComplexField(30); x := C.1; x;
C := ComplexField(20); x;
D := ComplexField(30); x;
F := GF(9); y := F.1; y;
F := GF(25); y;
P := PolynomialRing(Rationals()); t := P.1; t;
P := PolynomialRing(GF(7)); t;
E := ComplexField(40); z := E.1; E2 := E; z;
delete E; z;
h := function() S := {1, 2}; return map< S -> S | x :-> x >; end function;
h();
k := function() R := Integers(); return map< R -> R | x :-> x >; end function;
k();
E := GF(3^5); z := E.1; E2 := E; z;
delete E; z;
E3 := E2; delete E2; z;
F := GF(7^3); a := F.1; G := F; F := 1; a;
L := [GF(11^3)]; b := L[1].1; b;
M := L[1]; b;
N := GF(13^3); c := N.1; P := N; N := 2; c;
Q := GF(17^3); d := Q.1; Q := 3; d;
R := Parent(d); d;
S := GF(19^3); e := S.1; T := S; S := 4; U := T; T := 5; e;
f := function() V := GF(23^3); return V.1; end function;
g := f(); g;
W := Parent(g); g;
A1 := GF(29^2); B1 := GF(31^2);
u := A1.1;
B1 := A1; u;
delete A1; u;
A1 := B1; u;
X1 := 0; Y1 := GF(37^2); v := Y1.1; X1 := Y1; v;
Y1 := 0; v;
E := GF(41^2); z := E.1; E2 := E; E := 0; z;
E := GF(43^2); w := E.1; E2 := E; w;
F := GF(47^2); z := F.1; F2 := 5; delete F; F := GF(53^2); w := F.1; F2 := F; w;
A := GF(59^2); B := GF(61^2); u := A.1; B := A; A := 0; u;
A := B; u;
G := GF(67^2); g := G.1; delete G; G2 := 7; G := GF(71^2); g2 := G.1; G2 := G; g2;
H := GF(73^2); h := H.1; H2 := H; delete H; h; H := H2; h;
P1 := 1; P2 := 2; P3 := GF(79^2); p := P3.1;
delete P1; delete P2;
Q1 := P3;
Q2 := P3;
delete P3; p;
R1 := 1; R2 := 2; R3 := GF(83^2); r := R3.1;
delete R2; delete R1;
S1 := R3;
S2 := R3;
delete R3; r;
