// Attribute errors: invalid, unassigned and on objects without attributes.
Z := Integers();
Z`Unknown := 1;
Z`Unknown;
AddAttribute(RngInt, "Foo");
Z`Foo;
x := 3;
x`foo;
x`foo := 1;
f := func< a | a >;
f`foo;
assigned x`foo;
assigned Z`Unknown;
assigned Z`Foo;
Z`Foo := 5; Z`Foo;
assigned Z`Foo;
s := "abc"; s`foo;
L := [1, 2]; L`foo;
L`foo := 1;
t := <1, 2>; t`foo;
delete Z`Foo; Z`Foo;
delete Z`Bar;
delete x`foo;
R := rec< recformat< a > | a := 1 >; R`b;
R`b := 2;
assigned R`b;
Z`Unknown +:= 1;
AddAttribute(RngInt, "LongAttributeNameForWrappingTheLine"); Z`LongAttributeNameForWrappingTheLine;
try error "x"; catch e e`foo; end try;
Q := Rationals(); Q`Foo;
// Structures, aggregates and maps are structures; elements are objects.
S := {1}; S`foo;
S`foo := 1;
L := [* 1 *]; L`foo;
I := {@ 1 @}; I`foo;
M := {* 1 *}; M`foo;
h := hom< Integers() -> Integers() | x :-> x >; h`foo;
P<x> := PolynomialRing(Integers()); x`foo;
P`foo;
r := Integers(7)!3; r`foo;
q := 1/2; q`foo;
b := true; b`foo;
F := recformat< a >; F`foo;
A := AssociativeArray(); A`foo;
T := CartesianProduct(Integers(), Integers()); T`foo;
G := Sym(3); G`foo;
delete S`foo;
delete L`foo;
x`foo +:= 1;
S`foo +:= 1;
