// Factorization sequences (RngIntEltFact): creation, arithmetic, divisor
// functions, predicates, and which sequence operations keep the type.
f := Factorization(360); g := Factorization(84);
Facint(f); FactorizationToInteger(g); Type(Facint(f));
s := SeqFact([<2, 3>, <5, 1>]); s; Type(s); SequenceToFactorization([<3, 1>]); SeqFact([]);
SeqFact([<5, 1>, <2, 3>]);
SeqFact([<4, 1>]);
SeqFact([<2, 0>]);
SeqFact([<2, -1>]);
SeqFact([<2, 1>, <2, 1>]);
SeqFact([2, 3]);
Eltseq(f); Type(Eltseq(f)); ElementToSequence(f); Parent(f);
f + g; f - g; f * g; f / g; f ^ 2; f ^ 0; g - f;
g / f;
f / Factorization(7);
f ^ -1;
f - f;
Factorization(1) - Factorization(1);
f + Factorization(1);
f * 2;
f eq g; f eq f; f ne g; f eq [<2, 3>, <3, 2>, <5, 1>]; f eq 360;
Lcm(f, g); Gcd(f, g); GCD(f, Factorization(7)); LCM(f, Factorization(1));
SquarefreeFactorization(f); SquarefreeFactorization(Factorization(1)); SquarefreeFactorization(Factorization(72));
MoebiusMu(f); MoebiusMu(Factorization(30)); MoebiusMu(Factorization(1));
Divisors(g); PrimeDivisors(f); NumberOfDivisors(f); SumOfDivisors(f);
IsOne(f); IsOne(Factorization(1)); IsOdd(f); IsOdd(Factorization(45)); IsEven(f); IsUnit(f); IsUnit(Factorization(1));
IsPrime(f); IsPrime(Factorization(7)); IsPrime(Factorization(1)); IsPrimePower(Factorization(8)); IsPrimePower(f); IsPrimePower(Factorization(1));
IsSquare(f); IsSquare(Factorization(36)); IsSquare(Factorization(1)); IsSquarefree(f); IsSquarefree(Factorization(30)); IsSquarefree(Factorization(1));
#f; f[2]; f[1][2]; [x[1] : x in f]; &*[x[1]^x[2] : x in f];
f[4];
f[1] := <7, 1>;
Append(f, <7, 1>);
f cat g;
Reverse(f);
Factorization(360) eq SeqFact([<2, 3>, <3, 2>, <5, 1>]);
<2, 3> in f; <2, 2> in f;
Sort(f);
Universe(f);
Min(f);
f := Factorization(360); f[1] := <7, 1>; Type(f); f;
f := Factorization(360); Append(~f, <7, 1>); Type(f);
f := Factorization(360); Type(f cat f); Type(Reverse(f)); Type(Sort(f)); Type(Append(f, <7,1>)); Type(Include(f, <7,1>)); Type(Exclude(f, <2,3>));
IsEmpty(Factorization(1)); [Factorization(12), Factorization(1)]; {Factorization(12)}; Seqset(Factorization(12)); Factorization(12) in [Factorization(12)];
f := Factorization(360); f[1]; f[#f]; f[1,2]; Universe(f); Parent(f); Category(f); IsDefined(f, 2);
Factorization(12) eq Factorization(12); Factorization(12) cmpeq Factorization(12); Factorization(12) cmpeq [<2,2>,<3,1>];
Facint(Factorization(12)^100) eq 12^100;
NumberOfDivisors([<2, 3>]); SumOfDivisors([<2, 3>]); MoebiusMu([<2, 3>]); DivisorSigma(1, [<2, 3>]);
Facint(Factorization(360)[1..2]);
Type(Factorization(360)[1..2]); Type(Factorization(360)[[1, 2]]);
Type([<2, 3>]);
x := Factorization(12); x[3] := <5, 1>; x; Type(x);
Factorization(12) - Factorization(360);
FactoredEulerPhiInverse(14); FactoredEulerPhiInverse(3); FactoredEulerPhiInverse(1); FactoredEulerPhiInverse(2);
CarmichaelLambda(Factorization(1)); CarmichaelLambda(2); EulerPhi(Factorization(1)); MoebiusMu(1);
SquarefreeFactorization(-12); SquarefreeFactorization(Factorization(12));
IsSquare(Factorization(1));
x := Factorization(12); x[1] := <3, 1>; x; Facint(x); IsPrime(x); IsSquare(x); x * Factorization(2);
