// AffineAlgebra< R, X | L >, $ in constructors, and P / J with its map.
A := AffineAlgebra< RationalField(), x, y | x^2 - y^2, x*y - 1 >;
A;
A.1^3;
Type(A);
P := PreimageRing(A); P;
B<a, b> := AffineAlgebra< GF(5), x, y | x^2 - y, y^3 >;
B;
a^5;
C := AffineAlgebra< Integers(), t | t^2 + 1 >;
C;
D := AffineAlgebra< RationalField(), x, y | [x^2, y^2] >;
D;
E := AffineAlgebra< RationalField(), x, y | ideal< PolynomialRing(RationalField(), 2) | 1 > >;
F := AffineAlgebra< RationalField(), x, y | >;
F;
x;
G := AffineAlgebra< RationalField(), x, y | x^2 - y^2 : Global := true >;
P<x, y> := PolynomialRing(RationalField(), 2);
J := ideal< P | x^2 - y >;
P / J;
Q, f := P / J; f;
f(x^3);
quo< P | J >;
Q2 := quo< PolynomialRing(GF(5), 2, "grevlex") | $.1^3 - $.2, $.2^2 - 1 >;
Q2;
I := ideal< PolynomialRing(RationalField(), 2) | $.1^2, $.2 >;
I;
S := sub< Integers() | 2 >; S;
A := P / J; R := P / ideal< P | x >;
b := A subset R;
A subset R;
b := A eq R;
A eq R;
T := quo< Integers() | $ ! 6 >; T;
z := $;
