// Ideals of residue class rings.
R := Integers(12);
I := ideal<R | 8>; J := ideal<R | 6>;
I; J; I + J; I * J; I meet J; I eq J;
R!4 in I; R!6 in I; 4 in I; 13 in I; 16 in I;
K := sub<R | 0>; K;
L := ideal<R | 5>; L; L eq R;
Category(I); Type(I); Parent(I);
Modulus(I), #I, Modulus(K), #K;
Type(Generator(I)), Generator(I), Generator(K), Generator(R);
IsPrincipal(I);
I eq ideal<R | 4>, ideal<R | 4> eq sub<R | 8>, I meet R, I * I, I + I;
sub<R | [4, 6]>; sub<R | 4, 6>; sub<R | 5>;
ideal<R | Integers(24)!8>;
ideal<Integers(1) | 0>;
Characteristic(I), IsField(I), PrimeRing(I), Zero(I);
I!4;
I!5;
One(I);
Ngens(I);
IsPrime(I);
IsZero(K);
sub<R | 1/2>;
ideal<R | Integers(5)!2>;
I eq Integers();
I eq ideal<Integers(24) | 4>;
I + ideal<Integers(24) | 4>;
Integers(24)!4 in I;
S := Set(I); #S, Type(Universe(S)), Universe(S);
[x : x in I];
I2 := ideal<R | 8>; I2 eq I;
print I: Magma;
print K: Magma;
Sprint(I);

// Ideal division also returns the inclusion of the quotient (#50).
Z := Integers(); I := ideal<Z | 12>; J := ideal<Z | 4>;
K, f := I / J; K; f;
f(3); f(6); 3 @@ f;
Domain(f); Codomain(f);
K2, g := ideal<Z | 5> / ideal<Z | 10>;
Z := Integers(); I := ideal<Z | 12>; J := ideal<Z | 4>;
I / J;
Z / I;
K, f := Z / I;
