// Errors of Dirichlet characters: failed requirements name the intrinsic
// unless the call is a statement of its own (+ - * never name it), and
// failed coercions give their reasons.
DirichletGroup(0);
x := DirichletGroup(-5);
DirichletGroup(5, Integers(8));
DirichletGroup(5, RealField());
DirichletGroup(9, GF(7), GF(7)!3, 3);
DirichletGroup(5, Rationals(), -1, 2);
x := DirichletGroup(9, Integers(), -1, 1);
Elements(DirichletGroup(5, Rationals(), 1, 1));
G := DirichletGroup(5);
x := G.2;
print G.2;
[G.2];
x := G.-1;
Decomposition(DirichletGroup(1).1);
G![1];
G![1, 2];
G!3; G!0; G!(-1);
DirichletGroup(13, GF(27))![1];
DirichletGroup(13, GF(27))![3];
G!DirichletGroup(3).1;
DirichletGroup(5)!DirichletGroup(5, GF(7)).1;
DirichletGroup(4)!DirichletGroup(4, GF(5)).1;
DirichletGroup(5, GF(11))!DirichletGroup(5, GF(7)).1;
g7 := DirichletGroup(5, GF(7)).1;
IsCoercible(G, 1/2); IsCoercible(G, G.1); IsCoercible(G, 1); IsCoercible(G, [1]);
IsCoercible(G, DirichletGroup(10).1); IsCoercible(DirichletGroup(5, GF(11)), g7);
b, r := IsCoercible(G, "x"); b; r;
g7 * G.1;
y := g7 * G.1;
print g7 * G.1;
g7 / G.1;
y := g7 / G.1;
G.1 eq 1;
G.1 * 2;
G.1 ^ (1/2);
G.1 ^ "a";
Sqrt(DirichletGroup(35, GF(13)).1);
x := Sqrt(DirichletGroup(13, GF(27)).1);
H<b, c> := DirichletGroup(35, GF(13));
AssignNames(~H, ["u", "v", "w"]);
AssignNames(~H, ["u"]);
H.1;
GaloisConjugacyRepresentatives(H);
GaloisConjugacyRepresentatives([b, b^3, c]);
GaloisConjugacyRepresentatives(DirichletGroup(12, Integers()));
MinimalBaseRingCharacter(KroneckerCharacter(-4));
x := MinimalBaseRingCharacter(KroneckerCharacter(-4));
BaseExtend(H, GF(7));
BaseExtend(DirichletGroup(5, GF(7)), Rationals());
OrderOfRootOfUnity(GF(13)!3, 0);
Evaluate(b, 22/1);
for x in DirichletGroup(8) do x; end for;
