// The values of Dirichlet characters: Evaluate, chi(n) and n @ chi,
// ValueList and ValuesOnUnitGenerators, parities, conductors and orders of
// roots of unity.
G<a> := DirichletGroup(7, GF(7));
a; a^2; a^3; a^0; a^-1; a^6; a^7;
a(2); 2 @ a; a(-1); a(14); a(10^30 + 1);
Evaluate(a, 3); Evaluate(a, -3); Evaluate(a, 0);
ValueList(a);
ValuesOnUnitGenerators(a);
Order(a), Conductor(a), IsPrimitive(a), IsEven(a), IsOdd(a);
Eltseq(a^3); Order(a^3);
H<b, c> := DirichletGroup(35, GF(13));
UnitGenerators(H);
ValuesOnUnitGenerators(b*c);
Evaluate(b, 22); Evaluate(b, -13); Evaluate(b, 0);
b(Integers(35)!22); Evaluate(b, Integers(35)!22);
b(Integers(7)!3); b(Integers(70)!3); Evaluate(b, Integers(5)!2);
b(10^40 + 3); b(-10^40); b(35); (10^40 + 3) @ b;
[Conductor(x) : x in Elements(H)];
[Order(x) : x in Elements(H)];
[IsEven(x) : x in Elements(H)];
ValueList(DirichletGroup(9, GF(13)).1);
ValueList(DirichletGroup(13, GF(27)).1);
ValueList(DirichletGroup(7, GF(4)).1);
ValueList(DirichletGroup(5, GF(9)).1);
ValueList(DirichletGroup(16, GF(17)).2);
ValueList(DirichletGroup(9, GF(7), GF(7)!2, 6).1);
IsEven(DirichletGroup(9, GF(7), GF(7)!2, 6).1^3);
IsOdd(DirichletGroup(9, GF(7), GF(7)!2, 6).1^3);
IsOdd(DirichletGroup(7, GF(4)).1); IsEven(DirichletGroup(7, GF(4)).1);
ValueList(DirichletGroup(1).0); ValueList(DirichletGroup(2).0);
ValueList(KroneckerCharacter(-4, Rationals()));
ValueList(DirichletGroup(5, Integers()).1);
ValueList(KroneckerCharacter(5, GF(5)));
ValueList(KroneckerCharacter(-3) * KroneckerCharacter(-4));
G := DirichletGroup(24);
[Conductor(x) : x in Elements(G)];
[IsEven(x) : x in Elements(G)];
[IsTotallyEven(x) : x in Elements(G)];
IsTotallyEven(H.1^2); IsTotallyEven(H.1);
G := DirichletGroup(12);
[x : x in Elements(G) | IsPrimitive(x)];
Conductor(DirichletGroup(1).0); IsPrimitive(DirichletGroup(1).0); IsPrimitive(DirichletGroup(2).0);
[Conductor(x) : x in Elements(DirichletGroup(16, GF(17)))];
[Conductor(x) : x in Elements(DirichletGroup(100, GF(101)))];
OrderOfRootOfUnity(GF(13)!3, 12);
OrderOfRootOfUnity(-1, 2);
OrderOfRootOfUnity(GF(13)!3, 3);
OrderOfRootOfUnity(GF(13)!1, 12);
OrderOfRootOfUnity(GF(13)!2, 3);
OrderOfRootOfUnity(GF(13)!3, -3);
OrderOfRootOfUnity(Integers(8)!3, 2);
OrderOfRootOfUnity(2, 4);
[OrderOfRootOfUnity(Evaluate(b, n), 12) : n in [1..12] | GCD(n, 35) eq 1];
// Calls of values that are neither maps nor functions.
b(22/1);
x := b(22/1);
n := 5; n(2);
x := n(2);
