// Univariate polynomials: ideals and quotient rings (handbook, Univariate
// Polynomial Rings, Ideals and Quotient Rings).
P<x> := PolynomialRing(Rationals());
T<t> := PolynomialRing(GF(3));
Z<z> := PolynomialRing(Integers());

// Creation of ideals: the ideal is generated by the monic gcd, and the
// ideal generated by a unit is the ring itself.
I := ideal<P | x^2 - 1, x^3 - 1>;
I;
Type(I);
I.1;
ideal<P | 0>;
ideal<P | 3>;
ideal<P | 2*x + 2>;
ideal<P | [x^2 - 1, x^2 + 2*x + 1]>;
ideal<P | x^2 + 1> eq ideal<P | 2*x^2 + 2>;
ideal<T | t^2 + 1>;
ideal<Z | z^2 + 1, 2>;

// Ideal arithmetic.
J := ideal<P | x + 1>;
I + J; I * J; I meet J;
I eq J, I subset J, J subset I, I ne J, I notsubset J;
x - 1 in I, x in I, x^2 - 1 in I, 3 in I, x notin I;
I.1 in I;
I ! (x^2 - 1);
I ! x;

// Other functions on ideals.
K := ideal<P | x^2 + 1>;
Generators(K);
x^2 + 1 in K, (x^2 + 1)*x in K;
IsPrime(K), IsMaximal(K), IsPrincipal(K);
IsPrime(ideal<P | x^2 - 1>), IsMaximal(ideal<P | x^2 - 1>), IsPrime(ideal<P | 0>), IsMaximal(ideal<P | 0>);

// Quotients.
Q<q> := quo<P | x^2 + 1>;
Q;
Type(Q);
q;
Type(q);
Parent(q);
q^2, q^3, q^4, 1/q, q + 1, (q + 1)^-1, 2*q + 3/2;
-q, (q + 1)^2, q^0, q^-2;
Q.1;
Name(Q, 1);
Modulus(Q);
Parent(Modulus(Q));
PreimageRing(Q);
BaseRing(Q), CoefficientRing(Q);
Q2, h := quo<P | I>;
Q2;
h;
h(x^3);
Q3, h3 := quo<P | x^2 - 1, x^3 - 1>;
Q3;
h3;
quo<P | 0>;
quo<P | 1>;
quo<P | x^2, x^3 + x^2>;
Q4 := quo<P | K>;
Q4;

// Coercion.
Q ! x;
Q ! (x^5 + 3);
Q ! [1, 2, 3];
Q ! 5;
Q ! (1/2);
Q ! Q.1;
P ! q;
q eq Q!x, q ne Q!x;
q + x;
x + q;
q eq x;
Q ! t;
Q ! "x";

// Properties and element functions.
IsField(Q), IsField(Q2), IsDomain(Q), IsDomain(Q2), IsCommutative(Q);
Characteristic(Q);
#Q;
Coefficients(q^3 + 2), Degree(q^3 + 2), LeadingCoefficient(3*q + 1), Eltseq(3*q + 1);
Evaluate(x^2 + 1, q);
q div q;
q mod q;
Q5 := quo<P | x^3 - 2>;
Q5;
AssignNames(~Q5, ["r"]);
Q5;
Q5.1^3;

// Over finite fields.
F<a> := quo<T | t^2 + 1>;
F;
#F, IsField(F), IsDomain(F), Characteristic(F);
[k : k in F];
a^8, a^-1, a^4;
Random(F) in F;
R<b> := quo<T | t^2 - 1>;
#R, IsField(R), IsDomain(R);
b - 1;
(b - 1)^-1;
1/(b - 1);
(b + 2)*(b + 1);
IsUnit(b), IsUnit(b + 1), IsZero(b^2 - 1);
U<u> := PolynomialRing(GF(7));
E := quo<U | u^3 - 2>;
E;
E.1^3;
#E;
Order(E.1);
E2 := quo<U | (u - 1)^2>;
IsField(E2), IsDomain(E2);
E.1 eq E.1, E.1 eq 2;
2 eq E.1^3;

// Over rings that are not fields the modulus must be monic.
A<c> := quo<Z | z^2 + 1>;
A;
c^2, c^3 + 2*c, (c + 1)^2, 3*c - 5;
IsField(A), IsDomain(A), Characteristic(A);
c^-1;
(c + 1)^-1;
quo<Z | z^2 + 1>;
quo<Z | 2*z + 1>;
quo<Z | z^2 + 1, 2>;
quo<Z | 3>;
Y<y> := PolynomialRing(Integers(6));
B<d> := quo<Y | y^2 + 5>;
d^2, (d + 1)^3, #B;
quo<Y | 2*y + 1>;

// Printing.
Sprint(Q, "Magma");
Q6<w> := quo<P | x^2 - 2>;
w^2;
(w + 1)^-1;
Sprint(q, "Magma"), Sprint(Q!0, "Magma"), Sprint(a + 2, "Magma"), Sprint(c + 1, "Magma");
Sprint(A, "Magma");
// Magma prints the generator of an ideal in the variable x.
Sprint(ideal<P | x^2 - 1>, "Magma"), Sprint(ideal<P | 0>, "Magma"), Sprint(ideal<T | t^2 + 1>, "Magma");
