use crate::span::Span;

/// Reserved words of the Magma language, plus the word operators.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Kw {
    Adj,
    And,
    Assert,
    Assert2,
    Assert3,
    Assigned,
    Break,
    By,
    Case,
    Cat,
    Catch,
    Clear,
    Cmpeq,
    Cmpne,
    Continue,
    Declare,
    Default,
    Delete,
    Diff,
    Div,
    Do,
    Elif,
    Else,
    End,
    Eq,
    Error,
    Eval,
    Exists,
    Exit,
    False,
    For,
    Forall,
    Forward,
    Fprintf,
    Freeze,
    Function,
    Ge,
    Gt,
    If,
    Iload,
    Import,
    In,
    Intrinsic,
    Is,
    Join,
    Le,
    Load,
    Local,
    Lt,
    MarkSweep,
    Meet,
    Mod,
    Ne,
    Not,
    Notadj,
    Notin,
    Notsubset,
    Or,
    Print,
    Printf,
    Procedure,
    Quit,
    Random,
    Read,
    Readi,
    Repeat,
    Require,
    Requirege,
    Requirerange,
    Restore,
    Return,
    Save,
    Sdiff,
    Select,
    Subset,
    Then,
    Time,
    To,
    True,
    Try,
    Until,
    Vprint,
    Vprintf,
    Vtime,
    When,
    Where,
    While,
    Xor,
}

/// Every reserved word of the language.
pub const KEYWORDS: &[&str] = &[
    "adj", "and", "assert", "assert2", "assert3", "assigned", "break", "by", "case", "cat",
    "catch", "clear", "cmpeq", "cmpne", "continue", "declare", "default", "delete", "diff", "div",
    "do", "elif", "else", "end", "eq", "error", "eval", "exists", "exit", "false", "for", "forall",
    "forward", "fprintf", "freeze", "function", "ge", "gt", "if", "iload", "import", "in",
    "intrinsic", "is", "join", "le", "load", "local", "lt", "mark_sweep", "meet", "mod", "ne",
    "not", "notadj", "notin", "notsubset", "or", "print", "printf", "procedure", "quit", "random",
    "read", "readi", "repeat", "require", "requirege", "requirerange", "restore", "return", "save",
    "sdiff", "select", "subset", "then", "time", "to", "true", "try", "until", "vprint", "vprintf",
    "vtime", "when", "where", "while", "xor",
];

impl Kw {
    pub fn from_word(w: &str) -> Option<Kw> {
        use Kw::*;
        Some(match w {
            "adj" => Adj,
            "and" => And,
            "assert" => Assert,
            "assert2" => Assert2,
            "assert3" => Assert3,
            "assigned" => Assigned,
            "break" => Break,
            "by" => By,
            "case" => Case,
            "cat" => Cat,
            "catch" => Catch,
            "clear" => Clear,
            "cmpeq" => Cmpeq,
            "cmpne" => Cmpne,
            "continue" => Continue,
            "declare" => Declare,
            "default" => Default,
            "delete" => Delete,
            "diff" => Diff,
            "div" => Div,
            "do" => Do,
            "elif" => Elif,
            "else" => Else,
            "end" => End,
            "eq" => Eq,
            "error" => Error,
            "eval" => Eval,
            "exists" => Exists,
            "exit" => Exit,
            "false" => False,
            "for" => For,
            "forall" => Forall,
            "forward" => Forward,
            "fprintf" => Fprintf,
            "freeze" => Freeze,
            "function" => Function,
            "ge" => Ge,
            "gt" => Gt,
            "if" => If,
            "iload" => Iload,
            "import" => Import,
            "in" => In,
            "intrinsic" => Intrinsic,
            "is" => Is,
            "join" => Join,
            "le" => Le,
            "load" => Load,
            "local" => Local,
            "lt" => Lt,
            "mark_sweep" => MarkSweep,
            "meet" => Meet,
            "mod" => Mod,
            "ne" => Ne,
            "not" => Not,
            "notadj" => Notadj,
            "notin" => Notin,
            "notsubset" => Notsubset,
            "or" => Or,
            "print" => Print,
            "printf" => Printf,
            "procedure" => Procedure,
            "quit" => Quit,
            "random" => Random,
            "read" => Read,
            "readi" => Readi,
            "repeat" => Repeat,
            "require" => Require,
            "requirege" => Requirege,
            "requirerange" => Requirerange,
            "restore" => Restore,
            "return" => Return,
            "save" => Save,
            "sdiff" => Sdiff,
            "select" => Select,
            "subset" => Subset,
            "then" => Then,
            "time" => Time,
            "to" => To,
            "true" => True,
            "try" => Try,
            "until" => Until,
            "vprint" => Vprint,
            "vprintf" => Vprintf,
            "vtime" => Vtime,
            "when" => When,
            "where" => Where,
            "while" => While,
            "xor" => Xor,
            _ => return None,
        })
    }
}

/// A lexical token.
#[derive(Clone, Debug, PartialEq)]
pub enum Tok {
    /// An identifier, including quoted names such as `'+'`.
    Ident(String),
    /// A decimal integer literal (digits only).
    Int(String),
    /// A real literal, as written.
    Real(String),
    /// A string literal with escapes resolved.
    Str(String),
    Kw(Kw),
    /// `name o:=` mutation assignment, e.g. `+:=` or `join:=`.
    OpAssign(String),
    /// `$1`, `$2`, ...
    Dollar(u32),
    /// `$$`
    DollarDollar,
    Underscore,

    LParen,
    RParen,
    LBrack,
    RBrack,
    LBrace,
    RBrace,
    /// `{@`
    LBraceAt,
    /// `@}`
    AtRBrace,
    /// `{*`
    LBraceStar,
    /// `*}`
    StarRBrace,
    /// `{!`
    LBraceBang,
    /// `!}`
    BangRBrace,
    /// `[*`
    LBrackStar,
    /// `*]`
    StarRBrack,
    /// `[!`
    LBrackBang,
    /// `!]`
    BangRBrack,
    Lt,
    Gt,
    Comma,
    Semi,
    Colon,
    Dot,
    DotDot,
    Ellipsis,
    Assign,
    Plus,
    Minus,
    Star,
    Slash,
    Caret,
    CaretCaret,
    Hash,
    Tilde,
    Bang,
    BangBang,
    At,
    AtAt,
    Backquote,
    DoubleBackquote,
    Arrow,
    MapsTo,
    Pipe,
    Amp,
    Equals,
    Question,
    /// A malformed token; the message explains why.
    Error(String),
    /// Input ended inside a string or comment.
    Unterminated(String),
    Eof,
}

impl Tok {
    pub fn describe(&self) -> String {
        match self {
            Tok::Ident(s) => format!("identifier '{s}'"),
            Tok::Int(s) | Tok::Real(s) => format!("'{s}'"),
            Tok::Str(_) => "string".to_string(),
            Tok::Kw(k) => format!("'{}'", kw_text(*k)),
            Tok::OpAssign(o) => format!("'{o}:='"),
            Tok::Dollar(n) => format!("'${n}'"),
            Tok::Eof => "end of input".to_string(),
            Tok::Error(m) | Tok::Unterminated(m) => m.clone(),
            t => format!("'{}'", punct_text(t)),
        }
    }
}

pub fn kw_text(k: Kw) -> &'static str {
    use Kw::*;
    match k {
        Adj => "adj",
        And => "and",
        Assert => "assert",
        Assert2 => "assert2",
        Assert3 => "assert3",
        Assigned => "assigned",
        Break => "break",
        By => "by",
        Case => "case",
        Cat => "cat",
        Catch => "catch",
        Clear => "clear",
        Cmpeq => "cmpeq",
        Cmpne => "cmpne",
        Continue => "continue",
        Declare => "declare",
        Default => "default",
        Delete => "delete",
        Diff => "diff",
        Div => "div",
        Do => "do",
        Elif => "elif",
        Else => "else",
        End => "end",
        Eq => "eq",
        Error => "error",
        Eval => "eval",
        Exists => "exists",
        Exit => "exit",
        False => "false",
        For => "for",
        Forall => "forall",
        Forward => "forward",
        Fprintf => "fprintf",
        Freeze => "freeze",
        Function => "function",
        Ge => "ge",
        Gt => "gt",
        If => "if",
        Iload => "iload",
        Import => "import",
        In => "in",
        Intrinsic => "intrinsic",
        Is => "is",
        Join => "join",
        Le => "le",
        Load => "load",
        Local => "local",
        Lt => "lt",
        MarkSweep => "mark_sweep",
        Meet => "meet",
        Mod => "mod",
        Ne => "ne",
        Not => "not",
        Notadj => "notadj",
        Notin => "notin",
        Notsubset => "notsubset",
        Or => "or",
        Print => "print",
        Printf => "printf",
        Procedure => "procedure",
        Quit => "quit",
        Random => "random",
        Read => "read",
        Readi => "readi",
        Repeat => "repeat",
        Require => "require",
        Requirege => "requirege",
        Requirerange => "requirerange",
        Restore => "restore",
        Return => "return",
        Save => "save",
        Sdiff => "sdiff",
        Select => "select",
        Subset => "subset",
        Then => "then",
        Time => "time",
        To => "to",
        True => "true",
        Try => "try",
        Until => "until",
        Vprint => "vprint",
        Vprintf => "vprintf",
        Vtime => "vtime",
        When => "when",
        Where => "where",
        While => "while",
        Xor => "xor",
    }
}

fn punct_text(t: &Tok) -> &'static str {
    match t {
        Tok::DollarDollar => "$$",
        Tok::Underscore => "_",
        Tok::LParen => "(",
        Tok::RParen => ")",
        Tok::LBrack => "[",
        Tok::RBrack => "]",
        Tok::LBrace => "{",
        Tok::RBrace => "}",
        Tok::LBraceAt => "{@",
        Tok::AtRBrace => "@}",
        Tok::LBraceStar => "{*",
        Tok::StarRBrace => "*}",
        Tok::LBraceBang => "{!",
        Tok::BangRBrace => "!}",
        Tok::LBrackStar => "[*",
        Tok::StarRBrack => "*]",
        Tok::LBrackBang => "[!",
        Tok::BangRBrack => "!]",
        Tok::Lt => "<",
        Tok::Gt => ">",
        Tok::Comma => ",",
        Tok::Semi => ";",
        Tok::Colon => ":",
        Tok::Dot => ".",
        Tok::DotDot => "..",
        Tok::Ellipsis => "...",
        Tok::Assign => ":=",
        Tok::Plus => "+",
        Tok::Minus => "-",
        Tok::Star => "*",
        Tok::Slash => "/",
        Tok::Caret => "^",
        Tok::CaretCaret => "^^",
        Tok::Hash => "#",
        Tok::Tilde => "~",
        Tok::Bang => "!",
        Tok::BangBang => "!!",
        Tok::At => "@",
        Tok::AtAt => "@@",
        Tok::Backquote => "`",
        Tok::DoubleBackquote => "``",
        Tok::Arrow => "->",
        Tok::MapsTo => ":->",
        Tok::Pipe => "|",
        Tok::Amp => "&",
        Tok::Equals => "=",
        Tok::Question => "?",
        _ => "?",
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Token {
    pub tok: Tok,
    pub span: Span,
}
