//! Gröbner bases (the handbook chapter of that name): the functions on sets
//! and sequences of polynomials, and the functions that the ideals of
//! multivariate polynomial rings build on. The algorithms are in
//! calyx-groebner.
//!
//! As in Magma, a basis is sorted by decreasing leading monomial in the
//! ring's order, each polynomial monic over a field.

use std::rc::Rc;

use calyx_flint::gr::{Ctx, CtxKind, Elem};
use calyx_flint::{Integer, Rational};
use calyx_groebner::{self as gb, Order, Terms};

use super::mpoly::leading;
use super::{arg_ge, arg_not, boolv, one};
use crate::error::{RResult, RuntimeError};
use crate::interp::{CallArgs, Interp};
use crate::rings::{Ring, RingKind, make_elt, ring_of};
use crate::value::*;

// ----- the engine ------------------------------------------------------------

/// The terms of a polynomial, in any order.
fn terms(f: &Elem) -> Terms {
    (0..f.mpoly_len()).map(|i| f.mpoly_term(i)).collect()
}

/// The coefficient context, the rank and the monomial order of a
/// multivariate polynomial ring.
fn shape(r: &Ring) -> (&Rc<Ctx>, usize, &Order) {
    match &r.kind {
        RingKind::MPoly { rank, order, .. } => (r.ctx.base().expect("a polynomial ring"), *rank, order),
        _ => unreachable!("a multivariate polynomial ring"),
    }
}

/// The weights of the variables by which Magma measures the degree of a
/// pair: the grading of a graded ring, the weights of a grevlexw order,
/// and 1 otherwise.
fn pair_weights(r: &Ring) -> Vec<u64> {
    match &r.kind {
        RingKind::MPoly { grading: Some(w), .. } => w.to_vec(),
        RingKind::MPoly { order: Order::GRevLexW(w), .. } => w.clone(),
        RingKind::MPoly { rank, .. } => vec![1; *rank],
        _ => unreachable!("a multivariate polynomial ring"),
    }
}

/// Whether the coefficient ring of `r` is the real or the complex field.
fn inexact(r: &Ring) -> bool {
    match r.base() {
        Some(Value::Struct(s)) => match &s.kind {
            StructKind::Reals(_) => true,
            StructKind::Ring(b) => matches!(b.kind, RingKind::Complex(_)),
            _ => false,
        },
        _ => false,
    }
}

/// A result of the engine, as Magma words its errors. Magma computes over
/// Euclidean rings too, which the engine does not do yet.
fn engine<T>(r: &Ring, x: Result<T, gb::Error>) -> RResult<T> {
    x.map_err(|e| {
        RuntimeError::runtime(match e {
            gb::Error::Unsupported if inexact(r) => "Base ring must be an exact field or a Euclidean ring",
            gb::Error::Unsupported => "Algorithm is not available for this kind of coefficient ring",
            gb::Error::ExponentTooLarge => "Exponent is too large",
        })
    })
}

/// The reduced Gröbner basis in the ring's order of the ideal of the
/// multivariate polynomial ring `r` generated by `gens`: sorted by
/// decreasing leading monomial, monic, and empty for the zero ideal.
pub fn groebner_basis(r: &Ring, gens: &[Elem]) -> RResult<Vec<Elem>> {
    let (base, n, order) = shape(r);
    let g = engine(r, gb::groebner(base, n, order, &gens.iter().map(terms).collect::<Vec<_>>()))?;
    g.iter().map(|t| Ok(Elem::mpoly_from_terms(&r.ctx, t)?)).collect()
}

/// The normal form of `f` modulo `gb`, a Gröbner basis of the ideal of `r`
/// as `groebner_basis` gives it.
pub fn normal_form(r: &Ring, f: &Elem, gb: &[Elem]) -> RResult<Elem> {
    let (base, n, order) = shape(r);
    let nf = engine(r, gb::normal_form(base, n, order, &terms(f), &gb.iter().map(terms).collect::<Vec<_>>()))?;
    Ok(Elem::mpoly_from_terms(&r.ctx, &nf)?)
}

// ----- sets and sequences of polynomials -------------------------------------

/// The polynomials of a set or sequence argument, with their ring.
struct Polys {
    parent: Rc<Struct>,
    elems: Vec<Elem>,
}

impl Polys {
    fn ring(&self) -> &Ring {
        match &self.parent.kind {
            StructKind::Ring(r) => r,
            _ => unreachable!("a polynomial ring"),
        }
    }

    fn terms(&self) -> Vec<Terms> {
        self.elems.iter().map(terms).collect()
    }

    /// The polynomial of the ring with the terms `t`.
    fn elt(&self, t: &Terms) -> RResult<Value> {
        Ok(make_elt(&self.parent, Elem::mpoly_from_terms(&self.ring().ctx, t)?))
    }

    /// The sequence of the polynomials of the ring with the terms `ts`.
    fn seq(&self, ts: &[Terms]) -> RResult<Value> {
        let xs = ts.iter().map(|t| self.elt(t)).collect::<RResult<Vec<_>>>()?;
        Ok(Value::seq(Some(Value::Struct(self.parent.clone())), xs))
    }
}

/// Argument `i`, a set or sequence of polynomials.
fn polys(a: &CallArgs, i: usize) -> RResult<Polys> {
    let (universe, elems): (Option<&Value>, Vec<Value>) = match &a.args[i] {
        Value::Seq(q) => (q.universe.as_ref(), q.elems.clone()),
        Value::Set(s) => (s.universe.as_ref(), s.iter().collect()),
        _ => unreachable!("a set or sequence of polynomials"),
    };
    let Some((parent, _)) = universe.and_then(ring_of) else { return Err(RuntimeError::runtime("Illegal null argument")) };
    let elems = elems
        .iter()
        .map(|v| match v {
            Value::Elt(e) => e.x.clone(),
            _ => unreachable!("a polynomial"),
        })
        .collect();
    Ok(Polys { parent: parent.clone(), elems })
}

fn incompatible() -> RuntimeError {
    RuntimeError::runtime("Universe of argument 2 incompatible with argument 1")
}

/// `GroebnerBasis(S)`, `GroebnerBasisUnreduced(S)`: the reduced Gröbner
/// basis of the ideal generated by S.
fn groebner_basis_of(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let s = polys(a, 0)?;
    let r = s.ring();
    let (base, n, order) = shape(r);
    let g = engine(r, gb::groebner(base, n, order, &s.terms()))?;
    // The degrees of the steps of F4 and the denominators, which Magma
    // leaves unassigned here.
    let mut out = vals![s.seq(&g)?];
    out.extend((1..a.nresults.min(3)).map(|_| Value::Undef));
    Ok(out)
}

/// `GroebnerBasis(S, d)`: the basis truncated at weighted degree d.
fn truncated_basis(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let s = polys(a, 0)?;
    let d = a.int(1)?;
    if d.sign() < 0 {
        return Err(arg_ge(2, d, 0));
    }
    let d = d.to_i64().ok_or_else(|| RuntimeError::runtime(format!("Argument 2 ({d}) is too large")))?;
    let r = s.ring();
    let (base, n, order) = shape(r);
    let g = engine(r, gb::truncated_groebner(base, n, order, &s.terms(), &pair_weights(r), d as i128))?;
    one(s.seq(&g)?)
}

/// `NormalForm(f, S)`: the remainder of f on division by S, and for a
/// sequence the quotients.
fn normal_form_by(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let Value::Elt(f) = &a.args[0] else { unreachable!("a polynomial") };
    let f = f.clone();
    let s = polys(a, 1)?;
    if f.ring().id != s.ring().id {
        return Err(incompatible());
    }
    let r = s.ring();
    let (base, n, order) = shape(r);
    if a.nresults < 2 {
        let nf = engine(r, gb::normal_forms(base, n, order, &[terms(&f.x)], &s.terms()))?;
        return one(s.elt(&nf[0])?);
    }
    if matches!(a.args[1], Value::Set(_)) {
        return Err(RuntimeError::runtime("Second return value coordinates only possible when given a sequence"));
    }
    let (nf, q) = engine(r, gb::divide(base, n, order, &terms(&f.x), &s.terms()))?;
    Ok(vals![s.elt(&nf)?, s.seq(&q)?])
}

/// `NormalForm(FL, GL)`: the remainders of the polynomials of FL on
/// division by GL.
fn normal_forms_by(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let (fl, gl) = (polys(a, 0)?, polys(a, 1)?);
    if fl.ring().id != gl.ring().id {
        return Err(incompatible());
    }
    let r = gl.ring();
    let (base, n, order) = shape(r);
    one(fl.seq(&engine(r, gb::normal_forms(base, n, order, &fl.terms(), &gl.terms()))?)?)
}

/// `SPolynomial(f, g)`: LC(g) (L/LM(f)) f - LC(f) (L/LM(g)) g for the lcm L
/// of the leading monomials; over the rationals Magma first divides both
/// leading coefficients by their gcd.
fn s_polynomial(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let Value::Elt(f) = &a.args[0] else { unreachable!("a polynomial") };
    let f = f.clone();
    let g = it.to_ring_elem(&f.parent, &a.args[1], true)?.ok_or_else(|| RuntimeError::runtime("Arguments are not compatible"))?;
    let r = f.ring();
    let Some((cf, ef)) = leading(r, &f.x) else { return Err(arg_not(1, "non-zero")) };
    let Some((cg, eg)) = leading(r, &g) else { return Err(arg_not(2, "non-zero")) };
    let l: Vec<u64> = ef.iter().zip(&eg).map(|(x, y)| *x.max(y)).collect();
    let (cf, cg) = match cf.ctx().kind() {
        CtxKind::Rationals => {
            let (p, q) = (cf.to_rational()?, cg.to_rational()?);
            let d = Rational::new(&p.numerator().gcd(&q.numerator()), &p.denominator().lcm(&q.denominator())).expect("a non-zero gcd");
            let d = Elem::from_rational(cf.ctx(), &d)?;
            (cf.div(&d)?, cg.div(&d)?)
        }
        _ => (cf, cg),
    };
    // The terms of c (L/m) x.
    let shifted = |x: &Elem, c: &Elem, m: &[u64]| -> RResult<Terms> {
        terms(x)
            .into_iter()
            .map(|(k, e)| {
                let e = e.iter().zip(&l).zip(m).map(|((e, l), m)| e.checked_add(l - m)).collect::<Option<Vec<u64>>>();
                Ok((k.mul(c)?, e.ok_or_else(|| RuntimeError::runtime("Exponent is too large"))?))
            })
            .collect()
    };
    let mut ts = shifted(&f.x, &cg, &ef)?;
    ts.extend(shifted(&g, &cf.neg()?, &eg)?);
    one(make_elt(&f.parent, Elem::mpoly_from_terms(&r.ctx, &ts)?))
}

/// `Reduce(S)`: the polynomials of S reduced modulo each other until none
/// changes.
fn reduce(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let s = polys(a, 0)?;
    let r = s.ring();
    let (base, n, order) = shape(r);
    one(s.seq(&engine(r, gb::interreduce(base, n, order, &s.terms()))?)?)
}

/// `ReduceGroebnerBasis(S)`: the reduced basis of the ideal of which S is a
/// Gröbner basis.
fn reduce_groebner_basis(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let s = polys(a, 0)?;
    let r = s.ring();
    let (base, n, order) = shape(r);
    one(s.seq(&engine(r, gb::reduce_basis(base, n, order, &s.terms()))?)?)
}

/// `IsGroebner(S)`: whether S is a Gröbner basis of the ideal it generates.
fn is_groebner(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let s = polys(a, 0)?;
    let r = s.ring();
    let (base, n, order) = shape(r);
    boolv(engine(r, gb::is_groebner(base, n, order, &s.terms()))?)
}

/// The parameters of Magma's Gröbner basis functions that choose among
/// algorithms and strategies: they leave the result as it is, so they are
/// accepted and have no effect.
fn strategy_params() -> Vec<(&'static str, Value)> {
    let (yes, no) = (Value::Bool(true), Value::Bool(false));
    vec![
        ("Al", Value::str("Default")),
        ("Faugere", yes.clone()),
        ("Dense", no.clone()),
        ("HomogeneousWeights", yes.clone()),
        ("Homogenize", yes.clone()),
        ("GlobalModular", yes.clone()),
        ("AllPairs", no.clone()),
        ("PairsLimit", Value::Int(Integer::zero())),
        ("ReversePairs", no.clone()),
        ("HFE", no.clone()),
        ("Boolean", no.clone()),
        ("DynamicStrategy", no),
        ("Nthreads", Value::Int(Integer::one())),
        ("ReduceInitial", yes.clone()),
        ("RemoveRedundant", yes.clone()),
        ("ReduceByNew", yes),
    ]
}

pub fn register(it: &mut Interp) {
    let params = strategy_params();
    for s in ["S::[RngMPolElt]", "S::{RngMPolElt}"] {
        let sig = |rest: &str| format!("{s}{rest}");
        let doc = "The reduced Gröbner basis of the ideal generated by S.";
        it.def_params("GroebnerBasis", &sig(" -> [RngMPolElt], [RngIntElt]"), &params, doc, groebner_basis_of);
        let doc = "The Gröbner basis of the ideal generated by S truncated at degree d: the pairs of larger weighted degree are ignored.";
        it.def_params("GroebnerBasis", &sig(", d::RngIntElt -> [RngMPolElt]"), &params, doc, truncated_basis);
        it.def_params("GroebnerBasisUnreduced", &sig(" -> [RngMPolElt]"), &params, "A Gröbner basis of the ideal generated by S.", groebner_basis_of);
        it.def("IsGroebner", &sig(" -> BoolElt"), "Whether S is a Gröbner basis of the ideal it generates.", is_groebner);
        let doc = "The remainder of f on division by S, and for a sequence the quotients.";
        it.def("NormalForm", &format!("f::RngMPolElt, {s} -> RngMPolElt, [RngMPolElt]"), doc, normal_form_by);
        let doc = "The polynomials of S reduced modulo each other until none changes.";
        it.def_params("Reduce", &sig(" -> [RngMPolElt]"), &[("Faugere", Value::Bool(false))], doc, reduce);
        let doc = "The reduced Gröbner basis of the ideal of which S is a Gröbner basis.";
        it.def("ReduceGroebnerBasis", &sig(" -> [RngMPolElt]"), doc, reduce_groebner_basis);
        for fl in ["FL::[RngMPolElt]", "FL::{RngMPolElt}"] {
            let gl = s.replacen("S::", "GL::", 1);
            let doc = "The remainders of the polynomials of FL on division by GL.";
            it.def_params("NormalForm", &format!("{fl}, {gl} -> [RngMPolElt]"), &params, doc, normal_forms_by);
        }
    }
    it.def("SPolynomial", "f::RngMPolElt, g::RngMPolElt -> RngMPolElt", "The S-polynomial of f and g.", s_polynomial);
}
