//! Gröbner bases (the handbook chapter of that name): the functions on sets
//! and sequences of polynomials, and the functions that the ideals of
//! multivariate polynomial rings build on. The algorithms are in
//! calyx-groebner.
//!
//! As in Magma, a basis is sorted by decreasing leading monomial in the
//! ring's order, each polynomial monic over a field.

use std::rc::Rc;

use calyx_flint::gr::{Ctx, CtxKind, Elem, Truth};
use calyx_flint::{Integer, Rational};
use calyx_groebner::{self as gb, Order, Terms};

use super::mpoly::{leading, parse_order};
use super::poly_ideals::{Easy, EasyKind, MPolIdeal};
use super::{arg_ge, arg_not, boolv, one};
use crate::error::{RResult, RuntimeError};
use crate::interp::{CallArgs, Interp};
use crate::rings::props::ring_props;
use crate::rings::{Ring, RingKind, make_elt, ring_of};
use crate::value::*;

// ----- the engine ------------------------------------------------------------

/// The terms of a polynomial, in any order.
pub(super) fn terms(f: &Elem) -> Terms {
    (0..f.mpoly_len()).map(|i| f.mpoly_term(i)).collect()
}

/// The coefficient context, the rank and the monomial order of a
/// multivariate polynomial ring.
pub(super) fn shape(r: &Ring) -> (&Rc<Ctx>, usize, &Order) {
    match &r.kind {
        RingKind::MPoly { rank, order, .. } => (r.ctx.base().expect("a polynomial ring"), *rank, order),
        _ => unreachable!("a multivariate polynomial ring"),
    }
}

/// The weights of the variables by which Magma measures the degree of a
/// pair: the grading of a graded ring, the weights of a grevlexw order,
/// and 1 otherwise.
fn pair_weights(r: &Ring) -> Vec<u64> {
    match &r.kind {
        RingKind::MPoly { grading: Some(w), .. } => w.to_vec(),
        RingKind::MPoly { order: Order::GRevLexW(w), .. } => w.clone(),
        RingKind::MPoly { rank, .. } => vec![1; *rank],
        _ => unreachable!("a multivariate polynomial ring"),
    }
}

/// Whether the coefficient ring of `r` is the real or the complex field.
fn inexact(r: &Ring) -> bool {
    match r.base() {
        Some(Value::Struct(s)) => match &s.kind {
            StructKind::Reals(_) => true,
            StructKind::Ring(b) => matches!(b.kind, RingKind::Complex(_)),
            _ => false,
        },
        _ => false,
    }
}

/// A result of the engine, as Magma words its errors. Magma computes over
/// Euclidean rings too, which the engine does not do yet.
pub(super) fn engine<T>(r: &Ring, x: Result<T, gb::Error>) -> RResult<T> {
    x.map_err(|e| {
        RuntimeError::runtime(match e {
            gb::Error::Unsupported if inexact(r) => "Base ring must be an exact field or a Euclidean ring",
            gb::Error::Unsupported => "Algorithm is not available for this kind of coefficient ring",
            gb::Error::ExponentTooLarge => "Exponent is too large",
        })
    })
}

/// The reduced Gröbner basis in the ring's order of the ideal of the
/// multivariate polynomial ring `r` generated by `gens`: sorted by
/// decreasing leading monomial, monic, and empty for the zero ideal.
pub fn groebner_basis(r: &Ring, gens: &[Elem]) -> RResult<Vec<Elem>> {
    let (base, n, order) = shape(r);
    from_terms(r, &engine(r, gb::groebner(base, n, order, &gens.iter().map(terms).collect::<Vec<_>>()))?)
}

/// The reduced Gröbner basis in the order of `r` of the ideal whose easy
/// basis is `easy`: the easy basis in the ring's order, else by a change of
/// order (FGLM for a zero-dimensional ideal over GF(p)), else computed
/// again from the easy basis.
pub fn groebner_from_easy(r: &Ring, easy: &Easy) -> RResult<Vec<Elem>> {
    let (base, n, order) = shape(r);
    if easy.order == *order {
        return from_terms(r, &easy.terms);
    }
    from_terms(r, &engine(r, gb::change_order(base, n, &easy.order, &easy.terms, order))?)
}

/// The polynomials of `r` with the terms `ts`.
fn from_terms(r: &Ring, ts: &[Terms]) -> RResult<Vec<Elem>> {
    ts.iter().map(|t| Ok(Elem::mpoly_from_terms(&r.ctx, t)?)).collect()
}

/// The normal form of `f` modulo `gb`, a Gröbner basis of the ideal of `r`
/// as `groebner_basis` gives it.
pub fn normal_form(r: &Ring, f: &Elem, gb: &[Elem]) -> RResult<Elem> {
    let (base, n, order) = shape(r);
    let nf = engine(r, gb::normal_form(base, n, order, &terms(f), &gb.iter().map(terms).collect::<Vec<_>>()))?;
    Ok(Elem::mpoly_from_terms(&r.ctx, &nf)?)
}

// ----- sets and sequences of polynomials -------------------------------------

/// The polynomials of a set or sequence argument, with their ring.
struct Polys {
    parent: Rc<Struct>,
    elems: Vec<Elem>,
}

impl Polys {
    fn ring(&self) -> &Ring {
        match &self.parent.kind {
            StructKind::Ring(r) => r,
            _ => unreachable!("a polynomial ring"),
        }
    }

    fn terms(&self) -> Vec<Terms> {
        self.elems.iter().map(terms).collect()
    }

    /// The polynomial of the ring with the terms `t`.
    fn elt(&self, t: &Terms) -> RResult<Value> {
        Ok(make_elt(&self.parent, Elem::mpoly_from_terms(&self.ring().ctx, t)?))
    }

    /// The sequence of the polynomials of the ring with the terms `ts`.
    fn seq(&self, ts: &[Terms]) -> RResult<Value> {
        let xs = ts.iter().map(|t| self.elt(t)).collect::<RResult<Vec<_>>>()?;
        Ok(Value::seq(Some(Value::Struct(self.parent.clone())), xs))
    }
}

/// Argument `i`, a set or sequence of polynomials.
fn polys(a: &CallArgs, i: usize) -> RResult<Polys> {
    let (universe, elems): (Option<&Value>, Vec<Value>) = match &a.args[i] {
        Value::Seq(q) => (q.universe.as_ref(), q.elems.clone()),
        Value::Set(s) => (s.universe.as_ref(), s.iter().collect()),
        _ => unreachable!("a set or sequence of polynomials"),
    };
    let Some((parent, _)) = universe.and_then(ring_of) else { return Err(RuntimeError::runtime("Illegal null argument")) };
    let elems = elems
        .iter()
        .map(|v| match v {
            Value::Elt(e) => e.x.clone(),
            _ => unreachable!("a polynomial"),
        })
        .collect();
    Ok(Polys { parent: parent.clone(), elems })
}

fn incompatible() -> RuntimeError {
    RuntimeError::runtime("Universe of argument 2 incompatible with argument 1")
}

/// `GroebnerBasis(S)`, `GroebnerBasisUnreduced(S)`: the reduced Gröbner
/// basis of the ideal generated by S.
fn groebner_basis_of(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let s = polys(a, 0)?;
    let r = s.ring();
    let (base, n, order) = shape(r);
    let g = engine(r, gb::groebner(base, n, order, &s.terms()))?;
    // The degrees of the steps of F4 and the denominators, which Magma
    // leaves unassigned here.
    let mut out = vals![s.seq(&g)?];
    out.extend((1..a.nresults.min(3)).map(|_| Value::Undef));
    Ok(out)
}

/// `GroebnerBasis(S, d)`: the basis truncated at weighted degree d.
fn truncated_basis(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let s = polys(a, 0)?;
    let d = a.int(1)?;
    if d.sign() < 0 {
        return Err(arg_ge(2, d, 0));
    }
    let d = d.to_i64().ok_or_else(|| RuntimeError::runtime(format!("Argument 2 ({d}) is too large")))?;
    let r = s.ring();
    let (base, n, order) = shape(r);
    let g = engine(r, gb::truncated_groebner(base, n, order, &s.terms(), &pair_weights(r), d as i128))?;
    one(s.seq(&g)?)
}

/// `NormalForm(f, S)`: the remainder of f on division by S, and for a
/// sequence the quotients.
fn normal_form_by(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let Value::Elt(f) = &a.args[0] else { unreachable!("a polynomial") };
    let f = f.clone();
    let s = polys(a, 1)?;
    if f.ring().id != s.ring().id {
        return Err(incompatible());
    }
    let r = s.ring();
    let (base, n, order) = shape(r);
    if a.nresults < 2 {
        let nf = engine(r, gb::normal_forms(base, n, order, &[terms(&f.x)], &s.terms()))?;
        return one(s.elt(&nf[0])?);
    }
    if matches!(a.args[1], Value::Set(_)) {
        return Err(RuntimeError::runtime("Second return value coordinates only possible when given a sequence"));
    }
    let (nf, q) = engine(r, gb::divide(base, n, order, &terms(&f.x), &s.terms()))?;
    Ok(vals![s.elt(&nf)?, s.seq(&q)?])
}

/// `NormalForm(FL, GL)`: the remainders of the polynomials of FL on
/// division by GL.
fn normal_forms_by(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let (fl, gl) = (polys(a, 0)?, polys(a, 1)?);
    if fl.ring().id != gl.ring().id {
        return Err(incompatible());
    }
    let r = gl.ring();
    let (base, n, order) = shape(r);
    one(fl.seq(&engine(r, gb::normal_forms(base, n, order, &fl.terms(), &gl.terms()))?)?)
}

/// `SPolynomial(f, g)`: LC(g) (L/LM(f)) f - LC(f) (L/LM(g)) g for the lcm L
/// of the leading monomials; over the rationals Magma first divides both
/// leading coefficients by their gcd.
fn s_polynomial(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let Value::Elt(f) = &a.args[0] else { unreachable!("a polynomial") };
    let f = f.clone();
    let g = it.to_ring_elem(&f.parent, &a.args[1], true)?.ok_or_else(|| RuntimeError::runtime("Arguments are not compatible"))?;
    let r = f.ring();
    let Some((cf, ef)) = leading(r, &f.x) else { return Err(arg_not(1, "non-zero")) };
    let Some((cg, eg)) = leading(r, &g) else { return Err(arg_not(2, "non-zero")) };
    let l: Vec<u64> = ef.iter().zip(&eg).map(|(x, y)| *x.max(y)).collect();
    let (cf, cg) = match cf.ctx().kind() {
        CtxKind::Rationals => {
            let (p, q) = (cf.to_rational()?, cg.to_rational()?);
            let d = Rational::new(&p.numerator().gcd(&q.numerator()), &p.denominator().lcm(&q.denominator())).expect("a non-zero gcd");
            let d = Elem::from_rational(cf.ctx(), &d)?;
            (cf.div(&d)?, cg.div(&d)?)
        }
        _ => (cf, cg),
    };
    // The terms of c (L/m) x.
    let shifted = |x: &Elem, c: &Elem, m: &[u64]| -> RResult<Terms> {
        terms(x)
            .into_iter()
            .map(|(k, e)| {
                let e = e.iter().zip(&l).zip(m).map(|((e, l), m)| e.checked_add(l - m)).collect::<Option<Vec<u64>>>();
                Ok((k.mul(c)?, e.ok_or_else(|| RuntimeError::runtime("Exponent is too large"))?))
            })
            .collect()
    };
    let mut ts = shifted(&f.x, &cg, &ef)?;
    ts.extend(shifted(&g, &cf.neg()?, &eg)?);
    one(make_elt(&f.parent, Elem::mpoly_from_terms(&r.ctx, &ts)?))
}

/// `Reduce(S)`: the polynomials of S reduced modulo each other until none
/// changes.
fn reduce(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let s = polys(a, 0)?;
    let r = s.ring();
    let (base, n, order) = shape(r);
    one(s.seq(&engine(r, gb::interreduce(base, n, order, &s.terms()))?)?)
}

/// `ReduceGroebnerBasis(S)`: the reduced basis of the ideal of which S is a
/// Gröbner basis.
fn reduce_groebner_basis(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let s = polys(a, 0)?;
    let r = s.ring();
    let (base, n, order) = shape(r);
    one(s.seq(&engine(r, gb::reduce_basis(base, n, order, &s.terms()))?)?)
}

/// `IsGroebner(S)`: whether S is a Gröbner basis of the ideal it generates.
fn is_groebner(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let s = polys(a, 0)?;
    let r = s.ring();
    let (base, n, order) = shape(r);
    boolv(engine(r, gb::is_groebner(base, n, order, &s.terms()))?)
}

// ----- ideals ----------------------------------------------------------------

/// Argument `i`, an ideal of a multivariate polynomial ring or such a ring,
/// the ideal with basis [1].
fn ideal_arg(a: &CallArgs, i: usize) -> RResult<Rc<MPolIdeal>> {
    let Value::Struct(st) = &a.args[i] else { unreachable!("a polynomial ring or ideal") };
    match &st.kind {
        StructKind::MPolIdeal(id) => Ok(id.clone()),
        StructKind::Ring(r) => Ok(Rc::new(MPolIdeal::new(st.clone(), vec![Elem::one(&r.ctx)?], false))),
        _ => unreachable!("a polynomial ring or ideal"),
    }
}

/// Argument `i`, a polynomial of the ring of the ideal `id`.
fn member_arg(a: &CallArgs, i: usize, id: &MPolIdeal) -> RResult<Elem> {
    let Value::Elt(f) = &a.args[i] else { unreachable!("a polynomial") };
    if f.ring().id != id.poly_ring().id {
        return Err(RuntimeError::runtime("Arguments are not compatible"));
    }
    Ok(f.x.clone())
}

/// The sequence of the polynomials `xs` of the ring `pst`.
fn poly_seq(pst: &Rc<Struct>, xs: impl IntoIterator<Item = Elem>) -> Value {
    Value::seq(Some(Value::Struct(pst.clone())), xs.into_iter().map(|x| make_elt(pst, x)).collect())
}

/// `GroebnerBasis(I)`: the reduced Gröbner basis of I, which becomes its
/// basis.
fn ideal_groebner_basis(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let id = ideal_arg(a, 0)?;
    let g = id.groebner()?;
    // The degrees of the steps of F4, left unassigned as for sequences.
    let mut out = vals![poly_seq(&id.ring, g.iter().cloned())];
    out.extend((1..a.nresults.min(2)).map(|_| Value::Undef));
    Ok(out)
}

/// `Groebner(I)`: compute the Gröbner basis of I.
fn groebner_of(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    ideal_arg(a, 0)?.groebner()?;
    Ok(vals![])
}

/// `NormalForm(f, I)`: the normal form of f modulo the Gröbner basis of I.
fn normal_form_mod(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let id = ideal_arg(a, 1)?;
    let f = member_arg(a, 0, &id)?;
    one(make_elt(&id.ring, normal_form(id.poly_ring(), &f, &id.groebner()?)?))
}

/// `Coordinates(I, f)`: for f in I, polynomials c with f the sum of the c_i
/// times the elements of the Gröbner basis of I: the quotients of the
/// division of f by it.
fn coordinates(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let id = ideal_arg(a, 0)?;
    let f = member_arg(a, 1, &id)?;
    if id.fixed {
        return Err(RuntimeError::runtime("Coordinates for an ideal with a fixed basis are not implemented"));
    }
    let r = id.poly_ring();
    let (base, n, order) = shape(r);
    let g: Vec<Terms> = id.groebner()?.iter().map(terms).collect();
    let (rem, q) = engine(r, gb::divide(base, n, order, &terms(&f), &g))?;
    if !rem.is_empty() {
        return Err(RuntimeError::runtime("Argument 2 is not in argument 1"));
    }
    one(poly_seq(&id.ring, q.iter().map(|t| Elem::mpoly_from_terms(&r.ctx, t)).collect::<Result<Vec<_>, _>>()?))
}

/// `HasGroebnerBasis(I)`: whether the coefficient ring of I allows Gröbner
/// bases: an exact field or a Euclidean ring.
fn has_groebner_basis(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let id = ideal_arg(a, 0)?;
    boolv(id.poly_ring().base().and_then(ring_props).is_some_and(|p| p.exact && (p.field || p.magma_euclidean)))
}

/// A new polynomial ring with the coefficient ring, the rank and the names
/// of `r`, in the order `order`.
fn ring_like(it: &mut Interp, r: &Ring, order: Order) -> RResult<Rc<Struct>> {
    let (_, n, _) = shape(r);
    let q = it.mpoly_ring(r.base().expect("a polynomial ring"), n, order, None, false)?;
    let Some((qst, qr)) = ring_of(&q) else { unreachable!("a polynomial ring") };
    *qr.names.borrow_mut() = r.names.borrow().clone();
    Ok(qst.clone())
}

fn poly_ring_of(st: &Struct) -> &Ring {
    match &st.kind {
        StructKind::Ring(r) => r,
        _ => unreachable!("a polynomial ring"),
    }
}

/// The map from the polynomial ring `p` to `q`, of the same rank over the
/// same coefficient ring, that takes the variables of `p` to those of `q`
/// in turn.
fn ring_map(p: &Rc<Struct>, q: &Rc<Struct>) -> Value {
    Value::Map(Rc::new(MapObj { kind: MapKind::Map, domain: Value::Struct(p.clone()), codomain: Value::Struct(q.clone()), imp: MapImpl::Coercion }))
}

/// `f`, a polynomial of `r`, divided by its leading coefficient in the order
/// of `r`.
fn monic(r: &Ring, f: Elem) -> RResult<Elem> {
    match leading(r, &f) {
        Some((c, _)) if c.is_one() != Truth::True => Ok(f.mpoly_mul_scalar(&c.inv()?)?),
        _ => Ok(f),
    }
}

/// The ring of the easy basis of `id`: its own, or a new ring in the easy
/// order.
fn easy_ring(it: &mut Interp, id: &MPolIdeal, easy: &Easy) -> RResult<Rc<Struct>> {
    match easy.kind {
        EasyKind::Ring => Ok(id.ring.clone()),
        _ => ring_like(it, id.poly_ring(), easy.order.clone()),
    }
}

/// `EasyBasis(I)`: the Gröbner basis of I in the easy order, which Magma
/// chooses for the computations that allow any order.
fn easy_basis(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let id = ideal_arg(a, 0)?;
    let easy = id.easy()?;
    let qst = easy_ring(it, &id, &easy)?;
    one(poly_seq(&qst, from_terms(poly_ring_of(&qst), &easy.terms)?))
}

/// `EasyIdeal(I)`: the ideal E equal to I whose basis is the easy basis of
/// I, its Gröbner basis in the ring of the easy basis; the degrees of the
/// steps of F4, left unassigned; and the isomorphism from the ring of I to
/// that of E. A ring is its own easy ideal. As in Magma, a call statement
/// gives E alone.
fn easy_ideal(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let (e, f) = match a.args[0].as_struct() {
        Some(StructKind::MPolIdeal(id)) => {
            let id = id.clone();
            let easy = id.easy()?;
            let qst = easy_ring(it, &id, &easy)?;
            let e = MPolIdeal::new(qst.clone(), from_terms(poly_ring_of(&qst), &easy.terms)?, false);
            e.mark_groebner();
            (Value::structure(StructKind::MPolIdeal(Rc::new(e))), ring_map(&id.ring, &qst))
        }
        _ => {
            let Value::Struct(pst) = &a.args[0] else { unreachable!("a polynomial ring") };
            (a.args[0].clone(), ring_map(pst, pst))
        }
    };
    Ok(if a.nresults < 2 { vals![e] } else { vals![e, Value::Undef, f] })
}

/// `MarkGroebner(I)`: take the basis of I as it is for its Gröbner basis.
fn mark_groebner(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    if let Some(StructKind::MPolIdeal(id)) = a.args[0].as_struct() {
        id.mark_groebner();
    }
    Ok(vals![])
}

/// The ideal of `qst`, a polynomial ring of the rank of the ring P of `id`
/// over its coefficient ring, whose basis is the image of that of `id`, and
/// the map from P, which a call statement does not give. As in Magma the
/// basis is the easy basis once it is known, else the Gröbner basis once
/// known, each polynomial made monic in the new order, and else the basis as
/// given. A fixed basis takes no easy basis: Magma computes its Gröbner
/// basis directly.
fn ideal_in(a: &CallArgs, id: &MPolIdeal, qst: &Rc<Struct>) -> RResult<Vals> {
    let q = poly_ring_of(qst);
    let (ts, reduced): (Vec<Terms>, bool) = match id.known_easy().filter(|_| !id.fixed) {
        Some(easy) => (easy.terms.clone(), true),
        None if id.has_groebner() => (id.basis().iter().map(terms).collect(), true),
        None => (id.gens.iter().map(terms).collect(), false),
    };
    let mut basis = from_terms(q, &ts)?;
    if reduced && q.base().and_then(ring_props).is_some_and(|p| p.field) {
        basis = basis.into_iter().map(|f| monic(q, f)).collect::<RResult<_>>()?;
    }
    let j = MPolIdeal::new(qst.clone(), basis, false);
    j.learn_from(id);
    let j = Value::structure(StructKind::MPolIdeal(Rc::new(j)));
    Ok(if a.nresults < 2 { vals![j] } else { vals![j, ring_map(&id.ring, qst)] })
}

/// `ChangeOrder(I, Q)`: the ideal of Q corresponding to I, and the map from
/// the ring of I to Q.
fn change_order_to(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let id = ideal_arg(a, 0)?;
    let qst = match a.args[1].as_struct() {
        Some(StructKind::MPolIdeal(j)) => j.ring.clone(),
        _ => ring_of(&a.args[1]).expect("a polynomial ring").0.clone(),
    };
    let (p, q) = (id.poly_ring(), poly_ring_of(&qst));
    if shape(p).1 != shape(q).1 {
        return Err(RuntimeError::runtime("Arguments 1 and 2 have incompatible ranks"));
    }
    if p.base() != q.base() {
        return Err(RuntimeError::runtime("Arguments have incompatible coefficient rings"));
    }
    ideal_in(a, &id, &qst)
}

/// `ChangeOrder(I, order, ...)` and `ChangeOrder(I, <order, ...>)`: the
/// ideal corresponding to I in the ring with the order given, and the map
/// to that ring.
fn change_order_named(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let id = ideal_arg(a, 0)?;
    let n = shape(id.poly_ring()).1;
    let order = match &a.args[1] {
        Value::Str(s) => parse_order(n, s.as_str(), &a.args[2..], 3)?,
        Value::Tuple(t) => match t.elems.split_first() {
            Some((Value::Str(s), rest)) => parse_order(n, s.as_str(), rest, 2)?,
            _ => return Err(RuntimeError::runtime("First component of tuple must be a string")),
        },
        _ => unreachable!("an order"),
    };
    let qst = ring_like(it, id.poly_ring(), order)?;
    ideal_in(a, &id, &qst)
}

/// `SmallBasis(I)`: the shorter of the basis given and the Gröbner basis,
/// once known; the Gröbner basis when they are as long.
fn small_basis(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let id = ideal_arg(a, 0)?;
    let g = id.basis();
    let small = if id.has_groebner() && g.len() <= id.gens.len() { g } else { id.gens.clone() };
    one(poly_seq(&id.ring, small))
}

/// The parameters of Magma's Gröbner basis functions that choose among
/// algorithms and strategies: they leave the result as it is, so they are
/// accepted and have no effect.
fn strategy_params() -> Vec<(&'static str, Value)> {
    let (yes, no) = (Value::Bool(true), Value::Bool(false));
    vec![
        ("Al", Value::str("Default")),
        ("Faugere", yes.clone()),
        ("Dense", no.clone()),
        ("HomogeneousWeights", yes.clone()),
        ("Homogenize", yes.clone()),
        ("GlobalModular", yes.clone()),
        ("AllPairs", no.clone()),
        ("PairsLimit", Value::Int(Integer::zero())),
        ("ReversePairs", no.clone()),
        ("HFE", no.clone()),
        ("Boolean", no.clone()),
        ("DynamicStrategy", no),
        ("Nthreads", Value::Int(Integer::one())),
        ("ReduceInitial", yes.clone()),
        ("RemoveRedundant", yes.clone()),
        ("ReduceByNew", yes),
    ]
}

pub fn register(it: &mut Interp) {
    let params = strategy_params();
    for s in ["S::[RngMPolElt]", "S::{RngMPolElt}"] {
        let sig = |rest: &str| format!("{s}{rest}");
        let doc = "The reduced Gröbner basis of the ideal generated by S.";
        it.def_params("GroebnerBasis", &sig(" -> [RngMPolElt], [RngIntElt]"), &params, doc, groebner_basis_of);
        let doc = "The Gröbner basis of the ideal generated by S truncated at degree d: the pairs of larger weighted degree are ignored.";
        it.def_params("GroebnerBasis", &sig(", d::RngIntElt -> [RngMPolElt]"), &params, doc, truncated_basis);
        it.def_params("GroebnerBasisUnreduced", &sig(" -> [RngMPolElt]"), &params, "A Gröbner basis of the ideal generated by S.", groebner_basis_of);
        it.def("IsGroebner", &sig(" -> BoolElt"), "Whether S is a Gröbner basis of the ideal it generates.", is_groebner);
        let doc = "The remainder of f on division by S, and for a sequence the quotients.";
        it.def("NormalForm", &format!("f::RngMPolElt, {s} -> RngMPolElt, [RngMPolElt]"), doc, normal_form_by);
        let doc = "The polynomials of S reduced modulo each other until none changes.";
        it.def_params("Reduce", &sig(" -> [RngMPolElt]"), &[("Faugere", Value::Bool(false))], doc, reduce);
        let doc = "The reduced Gröbner basis of the ideal of which S is a Gröbner basis.";
        it.def("ReduceGroebnerBasis", &sig(" -> [RngMPolElt]"), doc, reduce_groebner_basis);
        for fl in ["FL::[RngMPolElt]", "FL::{RngMPolElt}"] {
            let gl = s.replacen("S::", "GL::", 1);
            let doc = "The remainders of the polynomials of FL on division by GL.";
            it.def_params("NormalForm", &format!("{fl}, {gl} -> [RngMPolElt]"), &params, doc, normal_forms_by);
        }
    }
    it.def("SPolynomial", "f::RngMPolElt, g::RngMPolElt -> RngMPolElt", "The S-polynomial of f and g.", s_polynomial);
    let doc = "The reduced Gröbner basis of the ideal I, which becomes its basis.";
    it.def_params("GroebnerBasis", "I::RngMPol -> [RngMPolElt], [RngIntElt]", &params, doc, ideal_groebner_basis);
    it.def_params("Groebner", "I::RngMPol", &params, "Compute the Gröbner basis of the ideal I.", groebner_of);
    it.def("NormalForm", "f::RngMPolElt, I::RngMPol -> RngMPolElt", "The normal form of f modulo the ideal I.", normal_form_mod);
    let doc = "Polynomials giving f, an element of the ideal I, as a combination of the Gröbner basis of I.";
    it.def("Coordinates", "I::RngMPol, f::RngMPolElt -> [RngMPolElt]", doc, coordinates);
    let doc = "Whether Gröbner bases can be computed over the coefficient ring of the ideal I.";
    it.def("HasGroebnerBasis", "I::RngMPol -> BoolElt", doc, has_groebner_basis);
    it.def("EasyBasis", "I::RngMPol -> [RngMPolElt]", "The Gröbner basis of the ideal I in the easy order.", easy_basis);
    let doc = "The ideal equal to I with its Gröbner basis in the easy order for basis, and the isomorphism onto it.";
    it.def("EasyIdeal", "I::RngMPol -> RngMPol, [RngIntElt], Map", doc, easy_ideal);
    it.def("MarkGroebner", "I::RngMPol", "Take the basis of the ideal I as it is for its Gröbner basis.", mark_groebner);
    let doc = "The ideal of Q corresponding to the ideal I, and the map from the ring of I to Q.";
    it.def("ChangeOrder", "I::RngMPol, Q::RngMPol -> RngMPol, Map", doc, change_order_to);
    let doc = "The ideal corresponding to the ideal I in the ring with the order given, and the map to that ring.";
    it.def("ChangeOrder", "I::RngMPol, order::MonStgElt, ... -> RngMPol, Map", doc, change_order_named);
    it.def("ChangeOrder", "I::RngMPol, T::Tup -> RngMPol, Map", doc, change_order_named);
    let doc = "The shorter of the basis of the ideal I as given and its Gröbner basis, once known.";
    it.def("SmallBasis", "I::RngMPol -> [RngMPolElt]", doc, small_basis);
}
