//! Functions on ideals of the integers (which are structures of type
//! `RngInt`, the integers themselves being the ideal generated by 1).

use std::rc::Rc;

use calyx_flint::Integer;
use calyx_syntax::ast::AggKind;

use super::{boolv, intv, one, require};
use crate::error::{RResult, RuntimeError};
use crate::interp::{CallArgs, Interp};
use crate::rings::ideals::int_ideal_gen;
use crate::types::t;
use crate::value::*;

fn generator(a: &CallArgs) -> Integer {
    int_ideal_gen(&a.args[0]).unwrap_or_default()
}

fn power_ideal(_it: &mut Interp, _a: &mut CallArgs) -> RResult<Vals> {
    one(Value::structure(StructKind::PowerStructure(t::RNG_INT)))
}

fn gen1(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    intv(generator(a))
}

fn gens(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    one(Value::int_seq([generator(a)]))
}

fn is_prime(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let n = generator(a);
    boolv(n.is_zero() || n.is_prime())
}

fn is_principal(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    Ok(vals![Value::Bool(true), Value::Int(generator(a))])
}

fn is_zero(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    boolv(generator(a).is_zero())
}

// ----- Z as a number field order --------------------------------------------

/// The generator of I, which must be a non-zero prime ideal.
fn prime_generator(a: &CallArgs) -> RResult<Integer> {
    let p = generator(a);
    if !p.is_prime() {
        return Err(require(RuntimeError::runtime("Argument must be a prime ideal")));
    }
    Ok(p)
}

fn decomposition(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let p = a.int(1)?.abs();
    if !p.is_prime() {
        return Err(require(RuntimeError::runtime("Argument 2 must be prime")));
    }
    let ideal = it.int_ideal(&p);
    one(it.build_aggregate(AggKind::Seq, None, vec![Value::tuple(vec![ideal, Value::int(1)])], false)?)
}

fn ramification_index(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    prime_generator(a)?;
    intv(Integer::one())
}

/// RamificationIndex(I, p) takes p only as the generator of I, not -p.
fn ramification_index_over(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let p = a.int(1)?;
    if !p.abs().is_prime() {
        return Err(require(RuntimeError::runtime("Argument 2 must be a prime")));
    }
    if &generator(a) != p {
        return Err(require(RuntimeError::runtime("Argument 1 must contain argument 2.")));
    }
    intv(Integer::one())
}

/// The inertia degree of a prime ideal, and the degree of Z itself.
fn degree(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    if !generator(a).is_one() {
        prime_generator(a)?;
    }
    intv(Integer::one())
}

fn two_element_normal(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let g = generator(a);
    Ok(vals![Value::Int(g.clone()), Value::Int(g)])
}

fn crt(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let ms = [generator(a), int_ideal_gen(&a.args[1]).unwrap_or_default()];
    intv(super::numtheory::crt_of(&[a.int(2)?.clone(), a.int(3)?.clone()], &ms)?)
}

/// The valuation at a prime ideal: both values always, as Magma's package
/// intrinsic returns them.
fn valuation(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let (n, p) = (a.int(0)?.clone(), int_ideal_gen(&a.args[1]).unwrap_or_default());
    super::ints::valuation_of(&n, &p, 2)
}

/// Z, the one class of ideals, with the identity map on it.
fn class_representative(_it: &mut Interp, _a: &mut CallArgs) -> RResult<Vals> {
    let z = Value::integers();
    let map = MapObj { kind: MapKind::Map, domain: z.clone(), codomain: z.clone(), imp: MapImpl::Coercion };
    Ok(vals![z, Value::Map(Rc::new(map))])
}

pub fn register(it: &mut Interp) {
    it.def("PowerIdeal", "R::RngInt -> PowStr", "The structure of the ideals of the integers.", power_ideal);
    it.def("Generator", "I::RngInt -> RngIntElt", "The non-negative generator of the ideal I.", gen1);
    for name in ["Generators", "Basis"] {
        it.def(name, "I::RngInt -> [RngIntElt]", "The generator of the ideal I, as a sequence.", gens);
    }
    for name in ["Norm", "Minimum"] {
        it.def(name, "I::RngInt -> RngIntElt", "The non-negative generator of the ideal I.", gen1);
    }
    it.def("IsPrime", "I::RngInt -> BoolElt", "Whether I is a prime ideal.", is_prime);
    it.def("IsPrincipal", "I::RngInt -> BoolElt, RngIntElt", "True, with a generator of I.", is_principal);
    it.def("IsZero", "I::RngInt -> BoolElt", "Whether I is the zero ideal.", is_zero);

    // Z as a number field order
    it.def("Decomposition", "Z::RngInt, p::RngIntElt -> SeqEnum", "The decomposition [ <pZ, 1> ] of the prime p.", decomposition);
    it.def("RamificationIndex", "I::RngInt -> RngIntElt", "The ramification index 1 of the prime ideal I.", ramification_index);
    it.def("RamificationIndex", "I::RngInt, p::RngIntElt -> RngIntElt", "The ramification index 1 of the prime ideal I = pZ over p.", ramification_index_over);
    it.def("Degree", "I::RngInt -> RngIntElt", "The inertia degree 1 of the prime ideal I (or the degree 1 of Z).", degree);
    it.def("TwoElementNormal", "I::RngInt -> RngIntElt, RngIntElt", "The generator of I, twice.", two_element_normal);
    it.def(
        "ChineseRemainderTheorem",
        "I::RngInt, J::RngInt, a::RngIntElt, b::RngIntElt -> RngIntElt",
        "The least x >= 0 with x - a in I and x - b in J, or -1.",
        crt,
    );
    it.def("Valuation", "x::RngIntElt, I::RngInt -> RngIntElt, RngIntElt", "The valuation v of x at the prime ideal I = pZ, and x/p^v.", valuation);
    it.def("ClassRepresentative", "I::RngInt -> RngInt, Map", "The representative Z of the class of I, with the identity map on Z.", class_representative);
}
