//! Functions on ideals of the integers (which are structures of type
//! `RngInt`, the integers themselves being the ideal generated by 1).

use calyx_flint::Integer;

use super::{boolv, intv, one};
use crate::error::RResult;
use crate::interp::{CallArgs, Interp};
use crate::rings::ideals::int_ideal_gen;
use crate::types::t;
use crate::value::*;

fn generator(a: &CallArgs) -> Integer {
    int_ideal_gen(&a.args[0]).unwrap_or_default()
}

fn power_ideal(_it: &mut Interp, _a: &mut CallArgs) -> RResult<Vec<Value>> {
    one(Value::structure(StructKind::PowerStructure(t::RNG_INT)))
}

fn gen1(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vec<Value>> {
    intv(generator(a))
}

fn gens(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vec<Value>> {
    one(Value::int_seq([generator(a)]))
}

fn is_prime(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vec<Value>> {
    let n = generator(a);
    boolv(n.is_zero() || n.is_prime())
}

fn is_principal(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vec<Value>> {
    Ok(vec![Value::Bool(true), Value::Int(generator(a))])
}

fn is_zero(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vec<Value>> {
    boolv(generator(a).is_zero())
}

pub fn register(it: &mut Interp) {
    it.def("PowerIdeal", "R::RngInt -> PowStr", "The structure of the ideals of the integers.", power_ideal);
    it.def("Generator", "I::RngInt -> RngIntElt", "The non-negative generator of the ideal I.", gen1);
    for name in ["Generators", "Basis"] {
        it.def(name, "I::RngInt -> [RngIntElt]", "The generator of the ideal I, as a sequence.", gens);
    }
    for name in ["Norm", "Minimum"] {
        it.def(name, "I::RngInt -> RngIntElt", "The non-negative generator of the ideal I.", gen1);
    }
    it.def("IsPrime", "I::RngInt -> BoolElt", "Whether I is a prime ideal.", is_prime);
    it.def("IsPrincipal", "I::RngInt -> BoolElt, RngIntElt", "True, with a generator of I.", is_principal);
    it.def("IsZero", "I::RngInt -> BoolElt", "Whether I is the zero ideal.", is_zero);
}
