// Handbook Part II, "Associative Arrays".
A := AssociativeArray();
A[1/2] := 7;
A[3/8] := "abc";
A[3] := 3/8;
A[1/2];
IsDefined(A, 3);
IsDefined(A, 4);
IsDefined(A, 3/8);
Keys(A);
Values(A);
for x in Keys(A) do x, A[x]; end for;
Remove(~A, 3/8);
IsDefined(A, 3/8);
Keys(A);
Values(A);
Universe(A);
#A;
A[99];
A := AssociativeArray(: Default := []);
x := 3; y := 5;
Append(~A[x], y);
assert A[x] eq [y];
assert Keys(A) eq {x};
assert Values(A) eq [* [ y ] *];
IsDefined(A, x);
IsInKeys(A, x);
IsDefined(A, 4);
IsInKeys(A, 4);
A := AssociativeArray(: Default := AssociativeArray(: Default := []));
Append(~A[1][2], 3);
Append(~A[1][2], 4);
Append(~A[5][6], 7);
A[1][2];
Keys(A);
Keys(A[5]);
A[9][9];
Keys(A);
A := AssociativeArray();
A[1/2] := 7;
A[3/8] := "abc";
A[3] := 3/8;
for k -> v in A do k, v; end for;
for v in A do v; end for;
// Index universes
B := AssociativeArray();
B[2] := "int";
B[1/3] := "rat";
Universe(B), Keys(B);
S := AssociativeArray(Strings());
S["one"] := 1;
S["two"] := 2;
S["one"] +:= 10;
S["one"];
S[1] := 3;
C := AssociativeArray();
C[[1, 2]] := "pair";
C[[1, 2]];
Universe(C);
A;
