// Environment, verbosity and session intrinsics.
SetColumns(40);
[ i : i in [1..30] ];
GetColumns();
SetColumns(80);
declare verbose MyFlag, 2;
SetVerbose("MyFlag", 1);
GetVerbose("MyFlag"), IsVerbose("MyFlag"), IsVerbose("MyFlag", 2);
vprint MyFlag: "shown";
vprint MyFlag, 2: "hidden";
SetVerbose("MyFlag", 3);
ClearVerbose();
GetVerbose("MyFlag");
t := Cputime();
Type(t);
Cputime(t) ge 0;
Type(Realtime());
SetPreviousSize(1);
1; 2;
$1;
$2;
GetPreviousSize();
SetPreviousSize(3);
v1, v2, v3 := GetVersion();
Type(v1);
x := 5;
ShowIdentifiers();
Load("pkgs/defs.m");
MY_LIMIT;
fred(4);
load "pkgs/defs.m";
Type(fred);
GetEnvironmentValue("CALYX_SURELY_UNSET_VARIABLE") eq "";
l := IsIntrinsic("Cputime"); l;
ListSignatures(FldRatElt);
