// A copy of compat/pending/integers_functions.m, so that calyx's output, checked against
// Magma 2.22, is kept until #24 records the output of 2.29.
// Arithmetic functions (Carmichael lambda, Dickman rho, divisor sums, Euler
// phi and its inverse, Legendre/Jacobi/Kronecker symbols, Moebius mu) and
// combinatorial functions. Dickman rho values are rounded to 15 digits.
CarmichaelLambda(1); CarmichaelLambda(8); CarmichaelLambda(16); CarmichaelLambda(15); CarmichaelLambda(561); CarmichaelLambda(2^10*3^4*7);
CarmichaelLambda(0);
CarmichaelLambda(-8);
CarmichaelLambda(Factorization(561)); CarmichaelLambda([<2, 3>, <3, 1>]);
FactoredCarmichaelLambda(561); Type(FactoredCarmichaelLambda(561)); FactoredCarmichaelLambda(1); FactoredCarmichaelLambda(Factorization(1000)); FactoredCarmichaelLambda([<2, 3>]);
DickmanRho(1); DickmanRho(0.5); DickmanRho(0); [Round(10^15*DickmanRho(u)) : u in [2, 3, 10]]; Round(10^15*DickmanRho(2.5));
DickmanRho(-1);
Round(10^15*DickmanRho(RealField(40)!3));
Round(10^15*DickmanRho(3/2));
DivisorSigma(0, 12); DivisorSigma(1, 12); DivisorSigma(2, 12); DivisorSigma(1, 1); DivisorSigma(3, Factorization(12));
DivisorSigma(1, 0);
DivisorSigma(1, -12);
DivisorSigma(-1, 12);
NumberOfDivisors(12); NumberOfDivisors(Factorization(720)); SumOfDivisors(28); SumOfDivisors(Factorization(28));
NumberOfDivisors(0);
NumberOfDivisors(-12);
SumOfDivisors(-12);
EulerPhi(1); EulerPhi(36); EulerPhi(Factorization(36)); EulerPhi([<2, 2>, <3, 2>]);
EulerPhi(0);
EulerPhi(-36);
FactoredEulerPhi(36); FactoredEulerPhi(Factorization(1000)); FactoredEulerPhi([<3, 2>]); FactoredEulerPhi(1); FactoredEulerPhi(2);
EulerPhiInverse(4); EulerPhiInverse(1); EulerPhiInverse(14); EulerPhiInverse(24); EulerPhiInverse(Factorization(24)); EulerPhiInverse(3);
EulerPhiInverse(0);
EulerPhiInverse(-4);
FactoredEulerPhiInverse(4); FactoredEulerPhiInverse(Factorization(8)); FactoredEulerPhiInverse(7);
LegendreSymbol(2, 7); LegendreSymbol(3, 7); LegendreSymbol(14, 7); LegendreSymbol(-1, 5);
LegendreSymbol(2, 9);
LegendreSymbol(2, 2);
LegendreSymbol(2, -7);
JacobiSymbol(2, 15); JacobiSymbol(7, 15); JacobiSymbol(5, 1); JacobiSymbol(-3, 9);
JacobiSymbol(2, 8);
JacobiSymbol(2, -15);
JacobiSymbol(2, 0);
KroneckerSymbol(2, 8); KroneckerSymbol(3, 8); KroneckerSymbol(-5, -3); KroneckerSymbol(5, 0); KroneckerSymbol(1, 0); KroneckerSymbol(-1, -1); KroneckerSymbol(0, -1);
MoebiusMu(1); MoebiusMu(6); MoebiusMu(12); MoebiusMu(30); MoebiusMu(Factorization(30));
MoebiusMu(0);
MoebiusMu(-6);
d := func< m | DivisorSigma(1, m)-m >; z := func< m | d(d(m)) eq m >; for m := 2 to 3000 do if z(m) then m, d(m); end if; end for;
Binomial(5, 2); Binomial(5, 0); Binomial(5, 6); Binomial(5, -1); Binomial(-5, 2); Binomial(0, 0); Binomial(100, 50);
Multinomial(6, [1, 2, 3]); Multinomial(4, [4]); Multinomial(0, []); Multinomial(3, [1, 1, 1]);
Multinomial(6, [1, 2, 2]);
Multinomial(6, [0, 6]);
Multinomial(6, [-1, 7]);
Factorial(0); Factorial(1); Factorial(10); Factorial(25);
Factorial(-1);
IsFactorial(120); IsFactorial(121); IsFactorial(1); IsFactorial(2); IsFactorial(0); IsFactorial(Factorial(30));
IsFactorial(-6);
Partitions(5); Partitions(1); Partitions(0); #Partitions(10);
Partitions(-1);
NumberOfPartitions(0); NumberOfPartitions(5); NumberOfPartitions(100); NumberOfPartitions(1000);
NumberOfPartitions(-1);
RestrictedPartitions(10, {2, 5}); RestrictedPartitions(10, {3}); RestrictedPartitions(0, {1}); RestrictedPartitions(7, {1, 2, 3});
RestrictedPartitions(10, 3, {1, 2, 3, 4}); RestrictedPartitions(10, 2, {5}); RestrictedPartitions(4, 0, {1});
RestrictedPartitions(10, {0, 2});
RestrictedPartitions(-1, {1});
RestrictedPartitions(10, [2, 5]);
StirlingFirst(5, 2); StirlingFirst(5, 5); StirlingFirst(5, 0); StirlingFirst(0, 0); StirlingFirst(3, 5); StirlingFirst(10, 3);
StirlingFirst(-1, 2);
StirlingSecond(5, 2); StirlingSecond(5, 5); StirlingSecond(5, 0); StirlingSecond(0, 0); StirlingSecond(3, 5); StirlingSecond(10, 3);
StirlingSecond(5, -1);
Bell(0); Bell(1); Bell(5); Bell(20);
Bell(-1);
Fibonacci(0); Fibonacci(10); Fibonacci(-10); Fibonacci(-11); Fibonacci(100);
Lucas(0); Lucas(10); Lucas(-10); Lucas(-11);
GeneralizedFibonacciNumber(0, 1, 10); GeneralizedFibonacciNumber(2, 1, 10); GeneralizedFibonacciNumber(3, 7, 5); GeneralizedFibonacciNumber(3, 7, -5); GeneralizedFibonacciNumber(3, 7, 0); GeneralizedFibonacciNumber(3, 7, 1);
GeneralizedFibonacciNumber(2, 5, -40); [ GeneralizedFibonacciNumber(3, -7, n) : n in [-6..6] ];
Fibonacci(2^30);
Fibonacci(-2^30);
Lucas(2^30);
GeneralizedFibonacciNumber(1, 1, 2^30);
