// Handbook Part I, "Input and Output".
// Strings
"\"Print this line in quotes\"";
"The first line,\nthe second line";
"Mag" cat "ma";
"Mag cat ma";
"73" * "9" * "42" eq "7" * "3942";
s := ("Mag" cat "ma? ")^2;
s, " "^5, s[4]^12, "!";
#s;
Eltseq("abc");
Substring("abcdefg", 3, 2);
Index("abcabc", "ca"), Position("abc", "z"), Position("", "");
StringToCode("A"), CodeToString(97);
StringToInteger("-0123"), StringToInteger("ff", 16), IntegerToString(255, 16);
StringToIntegerSequence("1 -2 +3   4");
IntegerToString(-42);
"ab" in "cabd", "x" notin "abc";
"Pi" le "magma", "magma" lt "pi";
Split("a b c d", " ");
Split("a||b|c", "|");
Split("a||b|c", "|" : IncludeEmpty := true);
Split("abxcdyefzab", "xyz");
Split("abcd", "");
Split("line1\nline2\n");
Regexp("b.*d", "abcde");
Regexp("b(.*)d", "abcde");
Regexp("b.*d", "xyz");
date := "Mon Jun 17 10:27:27 EST 1996";
_, _, f := Regexp("([0-9][0-9]):([0-9][0-9]):([0-9][0-9])", date);
f;
h, m, sec := Explode(f);
h, m, sec;
sc := StringToCode;
its := IntegerToString;
M := its(sc("M")) * its(sc("a")) * its(sc("g"));
M;
// print levels
print "abc", 1/2;
print "abc" : Magma;
print [ "x", "y" ] : Magma;
print Integers() : Magma;
[1, 2], 3 : Maximal;
// printf
for i := 1 to 150 by 33 do printf "[%3o]\n", i; end for;
for i := 1 to 150 by 33 do printf "[%-3o]\n", i; end for;
for w := 1 to 5 do printf "[%*o]", w, 1; end for;
printf "\n";
x := 3;
y := 4;
printf "x = %o, y = %o\n", x, y;
printf "G'"; printf "day\n";
p := 53.211;
x := 123.2;
printf "%.3o%% of %.2o is %.3o\n", p, x, p/100.0 * x;
printf "%h %m %O\n", 255, "q", [1], "Magma";
Q := [Sprintf("{%4o<->%-4o}", x, x): x in [1,10,100,1000]];
Q;
Sprint([1, 2]);
Sprint("a", "Magma");
printf "%o";
printf "%o\n", 1, 2;
// Previous values
1;
$1;
2, 3;
$1;
Quotrem(124124, 123);
$1;
a, b := $1;
a;
$2;
// Files
fn := Tempname("/tmp/calyx_io_test_");
PrintFile(fn, [1, 2, 3] : Overwrite := true);
PrintFile(fn, "second line");
Read(fn);
F := Open(fn, "r");
Gets(F);
Gets(F);
IsEof(Gets(F));
F := Open(fn, "w");
Puts(F, "hello");
Put(F, "world");
delete F;
Read(fn);
fprintf fn, "%o|%o\n", 1, 2;
Read(fn);
SetOutputFile(fn : Overwrite := true);
"this goes to the file";
UnsetOutputFile();
Read(fn);
System("rm " cat fn);
Pipe("tr a-z A-Z", "shout");
// Indentation
IndentPush();
"indented";
IndentPop();
"back";
