// Handbook Part II, "Mappings".
f := map< Integers() -> Integers() | x :-> x^2 >;
f;
f(3), 3 @ f;
{ 1, 2, 3 } @ f;
f([ 1, 2, 3 ]);
f(1/2);
g := map< Integers() -> Rationals() | x :-> x/2, y :-> Numerator(y) >;
g;
h := f * g;
h(4);
(1/2) @@ g;
Domain(h), Codomain(h);
Components(h);
Inverse(g)(7/2);
Inverse(f);
Function(f)(5);
HasPreimage(4, f), HasPreimage(1, g);
S := { 1, 2, 3 };
T := { "a", "b", "c" };
m := map< S -> T | 1 -> "a", 2 -> "b", 3 -> "c" >;
m(2);
"c" @@ m;
{ "a", "b" } @@ m;
m2 := map< S -> T | [ <1, "b">, <2, "b">, <3, "c"> ] >;
Image(m2);
IsInjective(m2), IsInjective(m), IsSurjective(m), IsBijective(m);
Graph(m);
map< S -> T | <1, "a"> >;
map< S -> T | <1, "a">, <1, "b">, <2, "a">, <3, "a"> >;
pm := pmap< S -> T | <1, "a"> >;
pm(1);
pm(2);
Coercion(Integers(), Rationals())(3);
Bang(Integers(), Rationals());
Parent(f);
Maps(Integers(), Rationals());
Domain(Maps(Integers(), Rationals()));
ExtendedType(f);
composite := m * map< T -> Integers() | x :-> StringToCode(x) >;
composite(3);
