// Handbook Part II, "Coproducts" and "Records".
C := cop<IntegerRing(), Strings()>;
x := C ! 5;
y := C ! "abc";
x;
y;
Parent(x);
x eq 5;
x eq y;
Retrieve(x);
Parent(Retrieve(x));
Index(x), Index(y);
#C, Constituent(C, 2);
C, m := cop< Integers(), Rationals() >;
z := m[2](1/2);
z, Index(z);
Injections(C);
Flat(cop< cop< Integers(), Booleans() >, Strings() >);
C := cop< [ Integers(), Booleans() ] >;
C;
C ! true;
C ! "no";
U := UniversalMap(cop< { 1, 2 }, { true } >, Integers(), [ map< { 1, 2 } -> Integers() | x :-> 10*x >, map< { true } -> Integers() | x :-> 0 > ]);
// Records
RF := recformat< n : Integers(), misc, seq : SeqEnum >;
RF;
Names(RF);
r := rec< RF | >;
r;
s := rec< RF | misc := "adsifaj", n := 42, seq := [ 4, 8, 1 ]>;
s;
t := rec< RF | seq := [ 4.7, 1.9 ], n := 51/3 >;
t;
Format(s) eq RF;
Names(s);
assigned r`seq;
r`seq := Append(t`seq, t`n); assigned r`seq;
r;
t``(s`misc);
u := rec< RF | misc := 5 >;
delete u``("m" cat "isc"); u;
rec< RF | n := 1/2 >;
rec< RF | seq := { 1 } >;
rec< RF | bogus := 1 >;
r`bogus;
s`n +:= 1;
s`n;
s`seq[2] := 0;
s`seq;
q := s;
q`n := 0;
s`n, q`n;
rec< recformat< a, b > | a := 1 >;
