// Handbook Part II, "Tuples and Cartesian Products" and "Lists".
C := car< RationalField(), Integers() >;
C;
CartesianProduct(Integers(), Booleans());
CartesianProduct([ Integers(), Rationals(), Integers() ]);
CartesianPower(Booleans(), 2);
#CartesianPower(Booleans(), 3);
Flat(car< car< Integers(), Rationals() >, Booleans() >);
NumberOfComponents(C), Component(C, 2), C[1];
Components(C);
Rep(car< Booleans(), Booleans() >);
C := car< Integers(), RationalField() >;
C ! < 26/13, 13/26 >;
elt< C | 3, 1/3 >;
C ! < 1/2, 1 >;
S := { C | <p, 1/p> : p in [1..25] | IsPrime(p) };
S;
[ t : t in car< Booleans(), { 1, 2 } > ];
// Tuples
f := < 11/2, 13/3, 7/5 >;
f;
#f;
Parent(f);
f[1] + f[2] + f[3];
f[3] := 7;
f;
<>;
T := < 1, "a" >;
Append(T, true);
Append(~T, [ 1 ]); T;
Prune(T);
Flat(< 1, < 2, < 3 > >, 4 >);
a, b := Explode(< 7, 8 >);
a, b;
TupleToList(< 1, "x" >), Tuplist(< 2 >);
< 1, 2 > eq < 1, 2 >, < 1, 2 > ne < 1, 3 >, < 1 > eq < 1/1 >;
for x in < 1, "b", true > do x; end for;
for i -> x in < "p", "q" > do i, x; end for;
IsEmpty(<>), IsEmpty(< 1 >);
&*< 2, 3/4 >;
< x^2 : x in [1..4] >;
// Lists
[* *];
L := [* 1, "a", [ 2 ] *];
L;
#L, L[2], IsEmpty(L);
L[4] := 4/5;
L;
L[7] := 0;
L cat [* true *];
Append(L, 9);
Append(~L, 10); #L;
Insert(~L, 1, "first"); L[1];
Prune(L);
SequenceToList([ 1, 2 ]), Seqlist([ 3 ]);
Reverse([* 1, 2, 3 *]);
L[ [ 1, 2 ] ];
IsDefined(L, 2), IsDefined(L, 99);
for x in [* 1, "z" *] do x; end for;
for i -> x in [* 3, 4 *] do i, x; end for;
[* 1, 2 *] eq [* 1, 2 *];
