//! Ideals of the integers and of residue class rings, and the `ideal< >`,
//! `quo< >` and `ext< >` constructors for the rings calyx has.
//!
//! As in Magma, an ideal of the integers is itself a structure of type
//! `RngInt`: `ideal<Z | 1>` is `Z`, and other ideals are `nZ` with a single
//! non-negative generator. Likewise an ideal of `R = Z/mZ` has type
//! `RngIntRes`: it is `dR` for a divisor `d` of `m`, and `R` itself when
//! `d = 1`. There is one of each, like the rings.

use std::rc::Rc;

use calyx_flint::Integer;
use calyx_syntax::ast::BinOp;

use super::RingKind;
use crate::error::{RResult, RuntimeError};
use crate::interp::Interp;
use crate::value::{MapImpl, MapKind, MapObj, Struct, StructKind, Value, struct_eq};

/// The non-negative generator of an ideal of the integers (1 for the
/// integers themselves).
pub fn int_ideal_gen(v: &Value) -> Option<Integer> {
    match v.as_struct()? {
        StructKind::Integers => Some(Integer::one()),
        StructKind::IntIdeal(n) => Some(n.clone()),
        _ => None,
    }
}

/// The modulus of a residue class ring.
pub fn residue_modulus(r: &Struct) -> Integer {
    match &r.kind {
        StructKind::Ring(ring) => match &ring.kind {
            RingKind::Residue(m) => m.clone(),
            _ => unreachable!("not a residue class ring"),
        },
        _ => unreachable!("not a residue class ring"),
    }
}

/// A residue class ring `R` or an ideal of one: `R` and the divisor `d` of
/// the modulus with the ideal `dR` (1 for `R` itself).
pub fn res_ideal_parts(v: &Value) -> Option<(Rc<Struct>, Integer)> {
    let Value::Struct(s) = v else { return None };
    match &s.kind {
        StructKind::Ring(r) if matches!(r.kind, RingKind::Residue(_)) => Some((s.clone(), Integer::one())),
        StructKind::ResIdeal(r, d) => Some((r.clone(), d.clone())),
        _ => None,
    }
}

/// A map given by coercion (an inclusion or a quotient map).
fn coercion_map(domain: Value, codomain: Value) -> Value {
    Value::Map(Rc::new(MapObj { kind: MapKind::Map, domain, codomain, imp: MapImpl::Coercion }))
}

/// The generator of the ideal generated by the integers `xs`.
fn gcd_all(xs: &[Integer]) -> Integer {
    xs.iter().fold(Integer::zero(), |g, x| g.gcd(x))
}

impl Interp {
    /// The ideal `nZ`.
    pub fn int_ideal(&mut self, n: &Integer) -> Value {
        let n = n.abs();
        if n.is_one() {
            return Value::integers();
        }
        self.rings.ideals.entry(n.clone()).or_insert_with(|| Value::structure(StructKind::IntIdeal(n))).clone()
    }

    /// The ideal of the residue class ring `ring` generated by `g`: `ring`
    /// itself when `g` is a unit.
    pub fn res_ideal(&mut self, ring: &Rc<Struct>, g: &Integer) -> Value {
        let d = g.gcd(&residue_modulus(ring));
        if d.is_one() {
            return Value::Struct(ring.clone());
        }
        let StructKind::Ring(r) = &ring.kind else { unreachable!() };
        self.rings.res_ideals.entry((r.id, d.clone())).or_insert_with(|| Value::structure(StructKind::ResIdeal(ring.clone(), d))).clone()
    }

    /// The elements of an ideal `dR` of `R = Z/mZ`: the multiples of `d`, in
    /// increasing order.
    pub fn enumerate_res_ideal(&mut self, st: &Rc<Struct>) -> RResult<Vec<Value>> {
        let StructKind::ResIdeal(r, d) = &st.kind else { unreachable!() };
        let StructKind::Ring(ring) = &r.kind else { unreachable!() };
        let size = residue_modulus(r).divexact(d);
        let n = size.to_u64().filter(|&n| n <= 1 << 26).ok_or_else(|| RuntimeError::runtime("The ring is too large to enumerate"))?;
        (0..n).map(|i| crate::intrinsics::residue::residue_value(r, ring, &(d * &Integer::from_u64(i)))).collect()
    }

    /// Operators on ideals of residue class rings (with at least one proper
    /// ideal among the operands).
    fn res_ideal_binop(&mut self, op: BinOp, (r, d): (Rc<Struct>, Integer), (s, e): (Rc<Struct>, Integer)) -> RResult<Option<Value>> {
        let same = struct_eq(&r, &s);
        if matches!(op, BinOp::Eq | BinOp::Ne) {
            return Ok(Some(Value::Bool((same && d == e) == (op == BinOp::Eq))));
        }
        if !matches!(op, BinOp::Add | BinOp::Mul | BinOp::Meet | BinOp::Subset | BinOp::Notsubset) {
            return Ok(None);
        }
        if !same {
            return Err(RuntimeError::runtime("Arguments are not compatible\nArgument types given: RngIntRes, RngIntRes").in_context(op.intrinsic_name()));
        }
        let m = residue_modulus(&r);
        Ok(Some(match op {
            BinOp::Add => self.res_ideal(&r, &d.gcd(&e)),
            BinOp::Mul => self.res_ideal(&r, &(&d * &e)),
            BinOp::Meet => self.res_ideal(&r, &d.lcm(&e).gcd(&m)),
            // dR is contained in eR when e divides d.
            _ => Value::Bool(d.is_divisible_by(&e) == (op == BinOp::Subset)),
        }))
    }

    /// Operators on ideals of the integers and of residue class rings.
    pub fn ideal_binop(&mut self, op: BinOp, a: &Value, b: &Value) -> RResult<Option<Value>> {
        if let Some(v) = crate::intrinsics::upoly::ideal_binop(self, op, a, b)? {
            return Ok(Some(v));
        }
        let is_ideal = |v: &Value| matches!(v.as_struct(), Some(StructKind::ResIdeal(..)));
        if is_ideal(a) || is_ideal(b) {
            return match (res_ideal_parts(a), res_ideal_parts(b)) {
                (Some(x), Some(y)) => self.res_ideal_binop(op, x, y),
                _ => Ok(None),
            };
        }
        let (Some(m), Some(n)) = (int_ideal_gen(a), int_ideal_gen(b)) else {
            return Ok(None);
        };
        // I is contained in J when the generator of J divides that of I.
        let contained = |m: &Integer, n: &Integer| {
            if n.is_zero() { m.is_zero() } else { m.div_rem_euclid(n).is_some_and(|(_, r)| r.is_zero()) }
        };
        Ok(Some(match op {
            BinOp::Add => self.int_ideal(&m.gcd(&n)),
            BinOp::Mul => self.int_ideal(&(&m * &n)),
            BinOp::Meet => self.int_ideal(&m.lcm(&n)),
            BinOp::Subset => Value::Bool(contained(&m, &n)),
            BinOp::Notsubset => Value::Bool(!contained(&m, &n)),
            // Ideal division, defined when J divides I. (Magma also
            // returns the inclusion of the quotient in Z.)
            BinOp::Div if n.is_zero() => return Err(RuntimeError::runtime("Division by zero").in_context("mod")),
            BinOp::Div if contained(&m, &n) => self.int_ideal(&m.divexact(&n).abs()),
            BinOp::Div => return Err(RuntimeError::runtime("Argument 2 must divide argument 1.")),
            _ => return Ok(None),
        }))
    }

    /// The integer generators of `ideal<Z | ...>` or `quo<Z | ...>`: integers,
    /// sequences of integers, and (for quotients) ideals.
    fn int_generators(&self, right: &[Value], ctx: &str) -> RResult<Vec<Integer>> {
        let invalid = |i: usize| RuntimeError::runtime(format!("Rhs argument {} is invalid for this constructor", i + 1)).in_context(ctx);
        let int_of = |v: &Value| match v {
            Value::Int(n) => Some(n.clone()),
            Value::Rat(q) if q.is_integral() => Some(q.numerator()),
            _ => None,
        };
        let mut out = Vec::new();
        for (i, v) in right.iter().enumerate() {
            match v {
                Value::Seq(s) => {
                    for e in &s.elems {
                        out.push(int_of(e).ok_or_else(|| invalid(i))?);
                    }
                }
                _ if int_of(v).is_some() => out.push(int_of(v).unwrap()),
                _ if int_ideal_gen(v).is_some() && ctx == "quo< ... >" => out.push(int_ideal_gen(v).unwrap()),
                _ => return Err(invalid(i)),
            }
        }
        Ok(out)
    }

    /// The gcd with the modulus of the generators of an ideal of the
    /// residue class ring `ring`: its elements (or elements coercible into
    /// it), integers, and sequences of these.
    fn res_generators(&mut self, ring: &Rc<Struct>, right: &[Value], ctx: &str) -> RResult<Integer> {
        let mut g = residue_modulus(ring);
        let target = Value::Struct(ring.clone());
        for (i, v) in right.iter().enumerate() {
            let items: Vec<Value> = match v {
                Value::Seq(s) => s.elems.clone(),
                _ => vec![v.clone()],
            };
            for x in items {
                let ok = match (&x, self.try_coerce(&target, &x)?) {
                    (Value::Int(_) | Value::Small(..) | Value::Elt(_), Ok(y)) => y,
                    _ => return Err(RuntimeError::runtime(format!("Rhs argument {} is invalid for this constructor", i + 1)).in_context(ctx)),
                };
                let rep = match &ok {
                    Value::Small(_, k) => Integer::from_u64(*k),
                    Value::Elt(e) => e.residue().unwrap_or_default(),
                    _ => unreachable!(),
                };
                g = g.gcd(&rep);
            }
        }
        Ok(g)
    }

    /// `ideal<R | ...>`: the ideal and its inclusion into R. `None` if R is
    /// not a ring calyx builds ideals of.
    pub fn ideal_constructor(&mut self, base: &Value, right: &[Value]) -> RResult<Option<Vec<Value>>> {
        if let Some(v) = crate::intrinsics::upoly::ideal_constructor(self, base, right)? {
            return Ok(Some(v));
        }
        if let Some((ring, 1)) = res_ideal_parts(base).map(|(r, d)| (r, d.to_u64().unwrap_or(0))) {
            let g = self.res_generators(&ring, right, "ideal< ... >")?;
            return Ok(Some(vec![self.res_ideal(&ring, &g)]));
        }
        if !matches!(base.as_struct(), Some(StructKind::Integers)) {
            return Ok(None);
        }
        let g = gcd_all(&self.int_generators(right, "ideal< ... >")?);
        let ideal = self.int_ideal(&g);
        let incl = coercion_map(ideal.clone(), base.clone());
        Ok(Some(vec![ideal, incl]))
    }

    /// `sub<Z | ...>`: the ideal generated (subrings of the integers are
    /// ideals) and its inclusion.
    pub fn sub_constructor(&mut self, base: &Value, right: &[Value]) -> RResult<Option<Vec<Value>>> {
        // Subrings of a residue class ring (or of an ideal of one) are the
        // ideals of the ring.
        if let Some((ring, _)) = res_ideal_parts(base) {
            let g = self.res_generators(&ring, right, "sub< ... >")?;
            return Ok(Some(vec![self.res_ideal(&ring, &g)]));
        }
        match base.as_struct() {
            Some(StructKind::Integers) => {}
            Some(StructKind::IntIdeal(_)) => return Err(RuntimeError::runtime("LHS must be all of Z, not just an ideal of it").in_context("sub< ... >")),
            _ => return Ok(None),
        }
        let g = gcd_all(&self.int_generators(right, "sub< ... >")?);
        let ideal = self.int_ideal(&g);
        let incl = coercion_map(ideal.clone(), base.clone());
        Ok(Some(vec![ideal, incl]))
    }

    /// `quo<R | ...>`: the quotient ring and the quotient map.
    pub fn quo_constructor(&mut self, base: &Value, right: &[Value]) -> RResult<Option<Vec<Value>>> {
        if let Some(v) = crate::intrinsics::upoly::quo_constructor(self, base, right)? {
            return Ok(Some(v));
        }
        if !matches!(base.as_struct(), Some(StructKind::Integers)) {
            return Ok(None);
        }
        let g = gcd_all(&self.int_generators(right, "quo< ... >")?);
        if g.is_zero() {
            return Err(RuntimeError::runtime("Illegal empty quotient").in_context("quo< ... >"));
        }
        let q = self.residue_ring(&g);
        let map = coercion_map(base.clone(), q.clone());
        Ok(Some(vec![q, map]))
    }

    /// `hom< D -> C | images >` given by the images of the generators of D
    /// (`vals` of a single sequence are its elements). `None` if D is not a
    /// structure whose homomorphisms calyx builds that way; each chapter adds
    /// the call for its structures here.
    pub fn hom_images(&mut self, kind: MapKind, domain: &Value, codomain: &Value, images: &[Value]) -> RResult<Option<Value>> {
        let _ = kind;
        if let Some(m) = crate::intrinsics::mpoly::polynomial_hom(self, domain, codomain, images)? {
            return Ok(Some(m));
        }
        Ok(None)
    }

    /// `ext<R | >`: the polynomial ring over R (a transcendental extension).
    pub fn ext_constructor(&mut self, left: &[Value], right: &[Value]) -> RResult<Option<Vec<Value>>> {
        if left.len() > 1 {
            return Err(RuntimeError::runtime("This constructer is no longer supported"));
        }
        if !right.is_empty() || crate::rings::props::ring_props(&left[0]).is_none() {
            return Ok(None);
        }
        Ok(Some(vec![self.poly_ring(&left[0], true)?]))
    }
}
