//! Ideals of the integers, and the `ideal< >`, `quo< >` and `ext< >`
//! constructors for the rings calyx has.
//!
//! As in Magma, an ideal of the integers is itself a structure of type
//! `RngInt`: `ideal<Z | 1>` is `Z`, and other ideals are `nZ` with a single
//! non-negative generator. There is one of each, like the rings.

use std::rc::Rc;

use calyx_flint::Integer;
use calyx_syntax::ast::BinOp;

use crate::error::{RResult, RuntimeError};
use crate::interp::Interp;
use crate::value::{MapImpl, MapKind, MapObj, StructKind, Value};

/// The non-negative generator of an ideal of the integers (1 for the
/// integers themselves).
pub fn int_ideal_gen(v: &Value) -> Option<Integer> {
    match v.as_struct()? {
        StructKind::Integers => Some(Integer::one()),
        StructKind::IntIdeal(n) => Some(n.clone()),
        _ => None,
    }
}

/// A map given by coercion (an inclusion or a quotient map).
fn coercion_map(domain: Value, codomain: Value) -> Value {
    Value::Map(Rc::new(MapObj { kind: MapKind::Map, domain, codomain, imp: MapImpl::Coercion }))
}

/// The generator of the ideal generated by the integers `xs`.
fn gcd_all(xs: &[Integer]) -> Integer {
    xs.iter().fold(Integer::zero(), |g, x| g.gcd(x))
}

impl Interp {
    /// The ideal `nZ`.
    pub fn int_ideal(&mut self, n: &Integer) -> Value {
        let n = n.abs();
        if n.is_one() {
            return Value::integers();
        }
        self.rings.ideals.entry(n.clone()).or_insert_with(|| Value::structure(StructKind::IntIdeal(n))).clone()
    }

    /// Operators on ideals of the integers.
    pub fn ideal_binop(&mut self, op: BinOp, a: &Value, b: &Value) -> RResult<Option<Value>> {
        let (Some(m), Some(n)) = (int_ideal_gen(a), int_ideal_gen(b)) else { return Ok(None) };
        // I is contained in J when the generator of J divides that of I.
        let contained = |m: &Integer, n: &Integer| if n.is_zero() { m.is_zero() } else { m.div_rem_euclid(n).is_some_and(|(_, r)| r.is_zero()) };
        Ok(Some(match op {
            BinOp::Add => self.int_ideal(&m.gcd(&n)),
            BinOp::Mul => self.int_ideal(&(&m * &n)),
            BinOp::Meet => self.int_ideal(&m.lcm(&n)),
            BinOp::Subset => Value::Bool(contained(&m, &n)),
            BinOp::Notsubset => Value::Bool(!contained(&m, &n)),
            BinOp::Div => return Err(RuntimeError::runtime("Argument 2 must divide argument 1.")),
            _ => return Ok(None),
        }))
    }

    /// The integer generators of `ideal<Z | ...>` or `quo<Z | ...>`: integers,
    /// sequences of integers, and (for quotients) ideals.
    fn int_generators(&self, right: &[Value], ctx: &str) -> RResult<Vec<Integer>> {
        let invalid = |i: usize| RuntimeError::runtime(format!("Rhs argument {} is invalid for this constructor", i + 1)).in_context(ctx);
        let int_of = |v: &Value| match v {
            Value::Int(n) => Some(n.clone()),
            Value::Rat(q) if q.is_integral() => Some(q.numerator()),
            _ => None,
        };
        let mut out = Vec::new();
        for (i, v) in right.iter().enumerate() {
            match v {
                Value::Seq(s) => {
                    for e in &s.elems {
                        out.push(int_of(e).ok_or_else(|| invalid(i))?);
                    }
                }
                _ if int_of(v).is_some() => out.push(int_of(v).unwrap()),
                _ if int_ideal_gen(v).is_some() && ctx == "quo< ... >" => out.push(int_ideal_gen(v).unwrap()),
                _ => return Err(invalid(i)),
            }
        }
        Ok(out)
    }

    /// `ideal<R | ...>`: the ideal and its inclusion into R. `None` if R is
    /// not a ring calyx builds ideals of.
    pub fn ideal_constructor(&mut self, base: &Value, right: &[Value]) -> RResult<Option<Vec<Value>>> {
        if !matches!(base.as_struct(), Some(StructKind::Integers)) {
            return Ok(None);
        }
        let g = gcd_all(&self.int_generators(right, "ideal< ... >")?);
        let ideal = self.int_ideal(&g);
        let incl = coercion_map(ideal.clone(), base.clone());
        Ok(Some(vec![ideal, incl]))
    }

    /// `quo<R | ...>`: the quotient ring and the quotient map.
    pub fn quo_constructor(&mut self, base: &Value, right: &[Value]) -> RResult<Option<Vec<Value>>> {
        if !matches!(base.as_struct(), Some(StructKind::Integers)) {
            return Ok(None);
        }
        let g = gcd_all(&self.int_generators(right, "quo< ... >")?);
        if g.is_zero() {
            return Err(RuntimeError::runtime("Illegal empty quotient").in_context("quo< ... >"));
        }
        let q = self.residue_ring(&g);
        let map = coercion_map(base.clone(), q.clone());
        Ok(Some(vec![q, map]))
    }

    /// `ext<R | >`: the polynomial ring over R (a transcendental extension).
    pub fn ext_constructor(&mut self, left: &[Value], right: &[Value]) -> RResult<Option<Vec<Value>>> {
        if left.len() > 1 {
            return Err(RuntimeError::runtime("This constructer is no longer supported"));
        }
        if !right.is_empty() || crate::rings::props::ring_props(&left[0]).is_none() {
            return Ok(None);
        }
        Ok(Some(vec![self.poly_ring(&left[0], true)?]))
    }
}
