[package]
name = "calyx-runtime"
description = "The calyx interpreter: values, types, evaluation and intrinsics"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
calyx-flint = { workspace = true }
calyx-groebner = { workspace = true }
calyx-syntax = { workspace = true }
indexmap = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
