[* [1], 2 *];
[* 1, [2], 3, [4] *];
[* 1, 2, <3, [4]> *];
[* *];
[ [* 1 *] ];
[ [* [1] *] ];
< [* [1] *], 2 >;
function f(x) return x; end function;
f;
g := function(x) return x + 1; end function;
g;
h := func<x | x^2>;
h;
procedure p(x) print x; end procedure;
p;
q := proc< | print 1 >;
q;
[ f ];
<f, 1>;
F<w> := GF(8);
{ w^3, w, 1, 0, w^6, w^2 };
K<u> := GF(2^30);
{ u, u^2, 1, 0 };
{ GF(7) | 3, 1, 6, 0 };
{ Integers(10) | 3, 1, 6, 0, 9 };
