RF := recformat< n : Integers(), misc, seq : SeqEnum >;
r := rec< RF | >;
r;
s := rec< RF | misc := "adsifaj", n := 42, seq := [ GF(13) | 4, 8, 1 ]>;
s;
[ s ];
<s, 1>;
s, 3;
t := rec< recformat<a, b> | a := 1 >;
t;
u := rec< RF | n := 1, seq := [ i^20 : i in [1..6] ] >;
u;
s := [1, 2];
s[0];
s[-1];
s[3] := 5;
s[3];
q := [1, 2, 3];
q[5] := 7;
q;
q[4];
Integers() ! [1];
Integers() ! 1.5;
Integers(6) ! (1/5);
Integers(6) ! (1/2);
x := 3/0;
y := 0; z := 3/y;
1.5/0;
