//! Buchberger's algorithm, with the criteria of Gebauer and Möller and the
//! sugar strategy. It works over any field: it is the reference that the
//! faster algorithms are checked against, and the algorithm for the fields
//! they don't cover.

use crate::field::Field;
use crate::poly::{Poly, Ring, coprime, degree, divides, lcm, mask, quotient, reduce, sub_mul};

struct Pair {
    i: usize,
    j: usize,
    lcm: Vec<u32>,
    sugar: u64,
}

struct State<'a, F: Field> {
    field: &'a F,
    ring: &'a Ring,
    /// Every polynomial added, monic.
    polys: Vec<Poly<F::E>>,
    masks: Vec<u64>,
    sugar: Vec<u64>,
    /// The current basis, as indices into `polys`: no leading monomial
    /// divides another.
    basis: Vec<usize>,
    pairs: Vec<Pair>,
    /// For a truncated basis, the weights of the variables and the largest
    /// weighted degree of the lcm of a pair that is considered.
    limit: Option<(&'a [u64], i128)>,
}

impl<F: Field> State<'_, F> {
    /// Add `h`, monic and reduced modulo the basis, and update the pairs and
    /// the basis (the UPDATE procedure of Gebauer and Möller).
    fn insert(&mut self, h: Poly<F::E>, sugar: u64) {
        let n = self.ring.n;
        let k = self.polys.len();
        let lm = h.lm(n).to_vec();
        self.masks.push(mask(&lm));
        self.polys.push(h);
        self.sugar.push(sugar);
        let mut new: Vec<(Pair, bool)> = self
            .basis
            .iter()
            .map(|&i| {
                let lm_i = self.polys[i].lm(n);
                let l = lcm(lm_i, &lm);
                let s = (self.sugar[i] + degree(&l) - degree(lm_i)).max(sugar + degree(&l) - degree(&lm));
                (Pair { i, j: k, lcm: l, sugar: s }, coprime(lm_i, &lm))
            })
            .collect();
        // Among the new pairs, drop one whose lcm is a multiple of the lcm of
        // another pair still in play (so one of each lcm survives), keeping
        // the coprime ones until this is done; then drop the coprime ones.
        let mut keep = vec![true; new.len()];
        for a in 0..new.len() {
            if !new[a].1 && (0..new.len()).any(|b| b != a && keep[b] && divides(&new[b].0.lcm, &new[a].0.lcm)) {
                keep[a] = false;
            }
        }
        let mut kept = keep.iter();
        new.retain(|(_, cop)| *kept.next().unwrap() && !cop);
        if let Some((w, d)) = self.limit {
            new.retain(|(p, _)| p.lcm.iter().zip(w).map(|(&e, &w)| e as i128 * w as i128).sum::<i128>() <= d);
        }
        // An old pair goes if lm(h) divides its lcm, unless its lcm is that
        // of one of its members with h.
        let polys = &self.polys;
        self.pairs.retain(|p| !divides(&lm, &p.lcm) || lcm(polys[p.i].lm(n), &lm) == p.lcm || lcm(polys[p.j].lm(n), &lm) == p.lcm);
        self.pairs.extend(new.into_iter().map(|(p, _)| p));
        self.basis.retain(|&i| !divides(&lm, polys[i].lm(n)));
        self.basis.push(k);
    }

    /// The pair of least sugar, and then of least lcm.
    fn select(&mut self) -> Option<Pair> {
        let ring = self.ring;
        let pairs = &self.pairs;
        let best = (0..pairs.len()).min_by(|&a, &b| pairs[a].sugar.cmp(&pairs[b].sugar).then_with(|| ring.cmp(&pairs[a].lcm, &pairs[b].lcm)))?;
        Some(self.pairs.swap_remove(best))
    }

    fn s_polynomial(&self, p: &Pair) -> Poly<F::E> {
        let n = self.ring.n;
        let (f, g) = (&self.polys[p.i], &self.polys[p.j]);
        let f = f.shift(&quotient(&p.lcm, f.lm(n)), n);
        // Both are monic, so the leading terms cancel.
        sub_mul(self.field, self.ring, &f, 1, &self.field.one(), &quotient(&p.lcm, g.lm(n)), g, 1)
    }

    /// Reduce `f` modulo the basis and add it unless it is zero; the unit
    /// ideal is reported as the constant polynomial.
    fn add(&mut self, f: Poly<F::E>, sugar: u64) -> Option<Poly<F::E>> {
        let mut h = reduce(self.field, self.ring, f, 0, &self.polys, &self.masks, &self.basis);
        if h.is_zero() {
            return None;
        }
        h.make_monic(self.field);
        if h.lm(self.ring.n).iter().all(|&x| x == 0) {
            return Some(h);
        }
        self.insert(h, sugar);
        None
    }
}

/// Reduce each polynomial of a minimal Gröbner basis modulo the others.
pub fn interreduce<F: Field>(field: &F, ring: &Ring, basis: Vec<Poly<F::E>>) -> Vec<Poly<F::E>> {
    let masks: Vec<u64> = basis.iter().map(|g| mask(g.lm(ring.n))).collect();
    (0..basis.len())
        .map(|k| {
            let others: Vec<usize> = (0..basis.len()).filter(|&j| j != k).collect();
            reduce(field, ring, basis[k].clone(), 1, &basis, &masks, &others)
        })
        .collect()
}

/// The reduced Gröbner basis of the ideal generated by `gens`: monic, sorted
/// by decreasing leading monomial. With a `limit` the pairs beyond it are
/// ignored, which gives a truncated basis.
pub fn groebner<F: Field>(field: &F, ring: &Ring, gens: Vec<Poly<F::E>>, limit: Option<(&[u64], i128)>) -> Vec<Poly<F::E>> {
    let n = ring.n;
    let mut gens: Vec<Poly<F::E>> = gens.into_iter().filter(|g| !g.is_zero()).collect();
    let mut st = State { field, ring, polys: Vec::new(), masks: Vec::new(), sugar: Vec::new(), basis: Vec::new(), pairs: Vec::new(), limit };
    if limit.is_none() {
        // Reduced as they come, from the least, the generators give a
        // smaller basis to start from.
        gens.sort_by(|a, b| ring.cmp(a.lm(n), b.lm(n)));
        for g in gens {
            let sugar = g.degree(n);
            if let Some(one) = st.add(g, sugar) {
                return vec![one];
            }
        }
    } else {
        // For a truncated basis Magma inserts the generators as they are,
        // in the order given: one whose leading monomial is a multiple of
        // another's is reduced by it only through their pair, which the
        // limit may exclude.
        for mut g in gens {
            g.make_monic(field);
            if g.lm(n).iter().all(|&x| x == 0) {
                return vec![g];
            }
            let sugar = g.degree(n);
            st.insert(g, sugar);
        }
    }
    while let Some(p) = st.select() {
        let s = st.s_polynomial(&p);
        if let Some(one) = st.add(s, p.sugar) {
            return vec![one];
        }
    }
    // Generators taken as they are may leave multiples in the basis.
    let polys = &st.polys;
    let minimal = st.basis.iter().filter(|&&k| !st.basis.iter().any(|&j| j != k && divides(polys[j].lm(n), polys[k].lm(n))));
    let mut g = interreduce(field, ring, minimal.map(|&k| polys[k].clone()).collect());
    g.sort_by(|a, b| ring.cmp(b.lm(n), a.lm(n)));
    g
}
