//! Gröbner bases for calyx.
//!
//! This crate holds the algorithms behind Magma's chapter on Gröbner bases:
//! the monomial orders and the computation of bases. It depends on
//! calyx-flint only, so the algorithms can be tested without the
//! interpreter; polynomials cross the boundary as lists of terms
//! `(coefficient, exponents)` in the coefficient ring's `gr` context, and
//! are converted once per call to the engine's own representation.

mod basis;
mod buchberger;
mod f4;
mod fglm;
pub mod field;
mod modular;
pub mod order;
mod poly;

use std::rc::Rc;

use calyx_flint::gr::{Ctx, CtxKind, Elem};

use field::{Coefficients, Field};
use poly::{Poly, Ring};

pub use order::{Order, OrderArg, OrderError, Weights};

/// A polynomial as a list of terms: a coefficient and the exponents of the
/// variables, in any order.
pub type Terms = Vec<(Elem, Vec<u64>)>;

/// How a basis is computed, as Magma's parameters choose it.
#[derive(Clone, Copy, Debug, Default)]
pub struct Strategy {
    /// Over the rationals, compute with rationals throughout rather than
    /// modulo primes (GlobalModular := false). The modular method is Monte
    /// Carlo, as in Magma; this way is proven.
    pub rational: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Error {
    /// The engine has no algorithm for this coefficient ring.
    Unsupported,
    /// An exponent of 2^32 or more.
    ExponentTooLarge,
}

/// Evaluate `$body` with `$f` bound to the engine's field for the
/// coefficient ring `$base`.
macro_rules! with_field {
    ($base:expr, $f:ident => $body:expr) => {
        match field::coefficients($base).ok_or(Error::Unsupported)? {
            Coefficients::Zp($f) => $body,
            Coefficients::Gr($f) => $body,
        }
    };
}

/// The reduced Gröbner basis of the ideal generated by `gens`, polynomials
/// in `n` variables over `base` with the monomial order `order`. As in
/// Magma, the basis is sorted by decreasing leading monomial and each
/// polynomial is monic with its terms in decreasing order; the zero ideal
/// has the empty basis.
pub fn groebner(base: &Rc<Ctx>, n: usize, order: &Order, gens: &[Terms]) -> Result<Vec<Terms>, Error> {
    groebner_with(base, n, order, gens, Strategy::default())
}

/// As `groebner`, computed as `strategy` says.
pub fn groebner_with(base: &Rc<Ctx>, n: usize, order: &Order, gens: &[Terms], strategy: Strategy) -> Result<Vec<Terms>, Error> {
    let ring = Ring { n, order: order.clone() };
    if modular(base, strategy) {
        if let Some(g) = modular::groebner(base, &ring, gens)? {
            return Ok(g);
        }
    }
    basis_of(base, &ring, gens, None)
}

/// Whether bases are lifted from bases modulo primes: over the rationals,
/// unless `strategy` says otherwise.
fn modular(base: &Ctx, strategy: Strategy) -> bool {
    !strategy.rational && matches!(base.kind(), CtxKind::Rationals)
}

/// The Gröbner basis of the ideal generated by `gens` truncated at degree
/// `d`: the pairs whose lcm has weighted degree more than `d`, the
/// variables having the weights `weights`, are ignored. It is reduced and
/// sorted as by `groebner`.
pub fn truncated_groebner(base: &Rc<Ctx>, n: usize, order: &Order, gens: &[Terms], weights: &[u64], d: i128) -> Result<Vec<Terms>, Error> {
    basis_of(base, &Ring { n, order: order.clone() }, gens, Some((weights, d)))
}

/// The normal form of `f` modulo `gb`, a Gröbner basis as `groebner`
/// returns it (with the same `base`, `n` and `order`).
pub fn normal_form(base: &Rc<Ctx>, n: usize, order: &Order, f: &Terms, gb: &[Terms]) -> Result<Terms, Error> {
    Ok(normal_forms(base, n, order, std::slice::from_ref(f), gb)?.pop().expect("one normal form"))
}

/// The remainders of the polynomials `fs` on division by `divisors` as in
/// `divide`: for a Gröbner basis, their normal forms.
pub fn normal_forms(base: &Rc<Ctx>, n: usize, order: &Order, fs: &[Terms], divisors: &[Terms]) -> Result<Vec<Terms>, Error> {
    let ring = Ring { n, order: order.clone() };
    with_field!(base, f => {
        let g = imports(&f, &ring, divisors)?;
        let active: Vec<usize> = (0..g.len()).filter(|&k| !g[k].is_zero()).collect();
        let masks: Vec<u64> = g.iter().map(|p| if p.is_zero() { 0 } else { poly::mask(p.lm(n)) }).collect();
        fs.iter().map(|t| Ok(export(&f, &ring, &poly::reduce(&f, &ring, import(&f, &ring, t)?, 0, &g, &masks, &active)))).collect()
    })
}

/// The division of `f` by `divisors`, which may include zeros, as Magma's
/// `NormalForm(f, S)` does it: the leading term of what is left is divided
/// by the first divisor whose leading monomial divides it, or else moves to
/// the remainder. Returns the remainder and the quotients.
pub fn divide(base: &Rc<Ctx>, n: usize, order: &Order, f: &Terms, divisors: &[Terms]) -> Result<(Terms, Vec<Terms>), Error> {
    let ring = Ring { n, order: order.clone() };
    with_field!(base, fld => {
        let (r, q) = poly::divide(&fld, &ring, import(&fld, &ring, f)?, &imports(&fld, &ring, divisors)?);
        Ok((export(&fld, &ring, &r), q.iter().map(|p| export(&fld, &ring, p)).collect()))
    })
}

/// The interreduction of `polys` as Magma's `Reduce` computes it: monic,
/// without zeros and sorted by decreasing leading monomial.
pub fn interreduce(base: &Rc<Ctx>, n: usize, order: &Order, polys: &[Terms]) -> Result<Vec<Terms>, Error> {
    let ring = Ring { n, order: order.clone() };
    with_field!(base, f => Ok(basis::interreduce(&f, &ring, imports(&f, &ring, polys)?).iter().map(|p| export(&f, &ring, p)).collect()))
}

/// The reduction of a Gröbner basis that need be neither minimal nor
/// reduced, as Magma's `ReduceGroebnerBasis` computes it.
pub fn reduce_basis(base: &Rc<Ctx>, n: usize, order: &Order, polys: &[Terms]) -> Result<Vec<Terms>, Error> {
    let ring = Ring { n, order: order.clone() };
    with_field!(base, f => Ok(basis::reduce_basis(&f, &ring, imports(&f, &ring, polys)?).iter().map(|p| export(&f, &ring, p)).collect()))
}

/// Whether `polys` is a Gröbner basis (not necessarily minimal or reduced)
/// of the ideal it generates.
pub fn is_groebner(base: &Rc<Ctx>, n: usize, order: &Order, polys: &[Terms]) -> Result<bool, Error> {
    let ring = Ring { n, order: order.clone() };
    with_field!(base, f => Ok(basis::is_groebner(&f, &ring, imports(&f, &ring, polys)?)))
}

/// The reduced Gröbner basis in the order `to` of the ideal of which `gb`
/// is the reduced Gröbner basis in the order `from`: for a zero-dimensional
/// ideal by a change of order, and otherwise computed again from `gb`.
pub fn change_order(base: &Rc<Ctx>, n: usize, from: &Order, gb: &[Terms], to: &Order) -> Result<Vec<Terms>, Error> {
    change_order_with(base, n, from, gb, to, Strategy::default())
}

/// As `change_order`, computed as `strategy` says.
pub fn change_order_with(base: &Rc<Ctx>, n: usize, from: &Order, gb: &[Terms], to: &Order, strategy: Strategy) -> Result<Vec<Terms>, Error> {
    let (ring, ring2) = (Ring { n, order: from.clone() }, Ring { n, order: to.clone() });
    let h = match field::coefficients(base).ok_or(Error::Unsupported)? {
        _ if modular(base, strategy) => modular::change_order(base, &ring, gb, &ring2)?,
        Coefficients::Zp(f) if f.modulus() < 1 << 31 => fglm::fglm(&f, &ring, &imports(&f, &ring, gb)?, &ring2).map(|h| exports(&f, &ring2, &h)),
        Coefficients::Zp(f) => fglm::fglm_field(&f, &ring, &imports(&f, &ring, gb)?, &ring2).map(|h| exports(&f, &ring2, &h)),
        Coefficients::Gr(f) => fglm::fglm_field(&f, &ring, &imports(&f, &ring, gb)?, &ring2).map(|h| exports(&f, &ring2, &h)),
    };
    match h {
        Some(h) => Ok(h),
        None => basis_of(base, &ring2, gb, None),
    }
}

/// Whether the order compares the degrees first, which suits the pairs of
/// F4 and Buchberger's algorithm taken by degree.
fn graded(order: &Order) -> bool {
    matches!(order, Order::GRevLex | Order::GLex | Order::GRevLexW(_))
}

/// A basis by F4 for the primes below 2^31, where it runs in word
/// arithmetic, and by Buchberger's algorithm for the other fields. As Magma
/// does, the basis in the other orders is computed in grevlex and changed to
/// the order, when the ideal is zero-dimensional. Over the rationals this
/// is the proven way.
fn basis_of(base: &Rc<Ctx>, ring: &Ring, gens: &[Terms], limit: Option<(&[u64], i128)>) -> Result<Vec<Terms>, Error> {
    match field::coefficients(base).ok_or(Error::Unsupported)? {
        Coefficients::Zp(f) if f.modulus() < 1 << 31 => Ok(exports(&f, ring, &words_basis(&f, ring, imports(&f, ring, gens)?, limit))),
        Coefficients::Zp(f) => changed_basis(&f, ring, gens, limit),
        Coefficients::Gr(f) => changed_basis(&f, ring, gens, limit),
    }
}

/// The basis over GF(p), p < 2^31, where F4 runs in words, of the ideal
/// generated by `polys`.
fn words_basis(f: &field::Zp, ring: &Ring, polys: Vec<Poly<u64>>, limit: Option<(&[u64], i128)>) -> Vec<Poly<u64>> {
    // F4 takes the pairs by degree, which suits graded orders and truncated
    // bases; in the other orders the degrees of the pairs can run far beyond
    // those of the basis.
    if limit.is_some() || graded(&ring.order) {
        // Pairs are taken by weighted degree for a grevlexw order.
        let weights = match (limit, &ring.order) {
            (Some((w, _)), _) => w.to_vec(),
            (None, Order::GRevLexW(w)) => w.clone(),
            _ => vec![1; ring.n],
        };
        return f4::groebner(f, ring, polys, &weights, limit.map(|(_, d)| d));
    }
    let grevlex = Ring { n: ring.n, order: Order::GRevLex };
    let g = f4::groebner(f, &grevlex, polys.iter().map(|p| reordered(f, p, &grevlex)).collect(), &vec![1; ring.n], None);
    fglm::fglm(f, &grevlex, &g, ring).unwrap_or_else(|| buchberger::groebner(f, ring, polys, None))
}

/// The polynomial `p` with its terms in the order of `ring`.
fn reordered<F: Field>(field: &F, p: &Poly<F::E>, ring: &Ring) -> Poly<F::E> {
    Poly::from_terms(field, ring, (0..p.len()).map(|i| (p.c[i].clone(), p.exp(i, ring.n).to_vec())).collect())
}

/// A basis by Buchberger's algorithm, in an order that is not graded by way
/// of grevlex for a zero-dimensional ideal.
fn changed_basis<F: Field>(field: &F, ring: &Ring, gens: &[Terms], limit: Option<(&[u64], i128)>) -> Result<Vec<Terms>, Error> {
    if limit.is_none() && !graded(&ring.order) {
        let grevlex = Ring { n: ring.n, order: Order::GRevLex };
        let g = buchberger::groebner(field, &grevlex, imports(field, &grevlex, gens)?, None);
        if let Some(h) = fglm::fglm_field(field, &grevlex, &g, ring) {
            return Ok(exports(field, ring, &h));
        }
    }
    groebner_in(field, ring, gens, limit)
}

fn exports<F: Field>(field: &F, ring: &Ring, polys: &[Poly<F::E>]) -> Vec<Terms> {
    polys.iter().map(|p| export(field, ring, p)).collect()
}

fn groebner_in<F: Field>(field: &F, ring: &Ring, gens: &[Terms], limit: Option<(&[u64], i128)>) -> Result<Vec<Terms>, Error> {
    let gens = imports(field, ring, gens)?;
    Ok(buchberger::groebner(field, ring, gens, limit).iter().map(|p| export(field, ring, p)).collect())
}

fn import<F: Field>(field: &F, ring: &Ring, t: &Terms) -> Result<Poly<F::E>, Error> {
    let exps = |e: &[u64]| e.iter().map(|&x| u32::try_from(x).map_err(|_| Error::ExponentTooLarge)).collect::<Result<Vec<u32>, Error>>();
    let terms = t.iter().map(|(c, e)| Ok((field.from_elem(c), exps(e)?))).collect::<Result<Vec<_>, Error>>()?;
    Ok(Poly::from_terms(field, ring, terms))
}

fn imports<F: Field>(field: &F, ring: &Ring, ts: &[Terms]) -> Result<Vec<Poly<F::E>>, Error> {
    ts.iter().map(|t| import(field, ring, t)).collect()
}

fn export<F: Field>(field: &F, ring: &Ring, p: &Poly<F::E>) -> Terms {
    (0..p.len()).map(|i| (field.to_elem(&p.c[i]), p.exp(i, ring.n).iter().map(|&x| x as u64).collect())).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use calyx_flint::gr::CtxKind;
    use calyx_flint::{Integer, Rational};

    /// A polynomial in the variables `vars` written as Magma prints it, such
    /// as `x^2*y - 3/2*z + 1`.
    pub fn parse(ctx: &Rc<Ctx>, vars: &str, s: &str) -> Terms {
        let names: Vec<char> = vars.chars().collect();
        let s: String = s.chars().filter(|c| !c.is_whitespace()).collect();
        let s = if s.starts_with('-') { s } else { format!("+{s}") };
        let mut terms = Terms::new();
        let mut rest = s.as_str();
        while !rest.is_empty() {
            let neg = rest.starts_with('-');
            rest = &rest[1..];
            let end = rest.find(['+', '-']).unwrap_or(rest.len());
            let (term, tail) = rest.split_at(end);
            rest = tail;
            let mut coeff = Rational::one();
            let mut e = vec![0u64; names.len()];
            for factor in term.split('*') {
                if factor.starts_with(|c: char| c.is_ascii_digit()) {
                    coeff = Rational::parse(factor).unwrap();
                } else {
                    let (v, k) = factor.split_once('^').unwrap_or((factor, "1"));
                    let i = names.iter().position(|&c| v.starts_with(c)).unwrap();
                    e[i] += k.parse::<u64>().unwrap();
                }
            }
            if neg {
                coeff = -&coeff;
            }
            let c = match ctx.kind() {
                CtxKind::Rationals => Elem::from_rational(ctx, &coeff).unwrap(),
                _ => Elem::from_integer(ctx, &coeff.numerator()).unwrap().div(&Elem::from_integer(ctx, &coeff.denominator()).unwrap()).unwrap(),
            };
            terms.push((c, e));
        }
        terms
    }

    /// Print a polynomial as Magma does, its terms in the order given.
    pub fn show(vars: &str, t: &Terms) -> String {
        let names: Vec<char> = vars.chars().collect();
        let mut out = String::new();
        for (c, e) in t {
            let q = match c.ctx().kind() {
                CtxKind::Rationals => c.to_rational().unwrap(),
                _ => Rational::from_integer(&c.to_integer().unwrap_or_else(|_| Integer::from_u64(c.to_word().unwrap()))),
            };
            let power = |k: u64, v: char| if k == 1 { v.to_string() } else { format!("{v}^{k}") };
            let mono: Vec<String> = e.iter().zip(&names).filter(|(k, _)| **k > 0).map(|(k, v)| power(*k, *v)).collect();
            let (neg, a) = (q.sign() < 0, q.abs());
            if out.is_empty() {
                out.push_str(if neg { "-" } else { "" });
            } else {
                out.push_str(if neg { " - " } else { " + " });
            }
            match (a.is_one(), mono.is_empty()) {
                (true, false) => out.push_str(&mono.join("*")),
                (_, true) => out.push_str(&a.to_string()),
                _ => out.push_str(&format!("{a}*{}", mono.join("*"))),
            }
        }
        if out.is_empty() { "0".into() } else { out }
    }

    pub fn gb(ctx: &Rc<Ctx>, vars: &str, order: &Order, gens: &[&str]) -> Vec<String> {
        let gens: Vec<Terms> = gens.iter().map(|s| parse(ctx, vars, s)).collect();
        groebner(ctx, vars.len(), order, &gens).unwrap().iter().map(|t| show(vars, t)).collect()
    }

    fn gf(p: u64) -> Rc<Ctx> {
        Ctx::residue_ring(&Integer::from_u64(p))
    }

    #[test]
    fn handbook_system_over_gf2() {
        let b = ["a*b + c*d + 1", "a*c*e + d*e", "a*b*e + c*e", "b*c + c*d*e + 1"];
        let g = [
            "a + c^2*d + c + d^2*e",
            "b*c + d^3*e^2 + d^3*e + d^2*e^2 + d*e + e + 1",
            "b*e + d*e^2 + d*e + e",
            "c*e + d^3*e^2 + d^3*e + d^2*e^2 + d*e",
            "d^4*e^2 + d^4*e + d^3*e + d^2*e^2 + d^2*e + d*e + e",
        ];
        assert_eq!(gb(&gf(2), "abcde", &Order::Lex, &b), g);
        let bb: Vec<&str> = b.iter().copied().chain(["a^2 + a", "b^2 + b", "c^2 + c", "d^2 + d", "e^2 + e"]).collect();
        assert_eq!(gb(&gf(2), "abcde", &Order::Lex, &bb), ["a + d + 1", "b + 1", "c + 1", "d^2 + d", "e"]);
    }

    #[test]
    fn handbook_primes_of_a_system_over_z() {
        let i = ["x^2 - 3*y", "y^3 - x*y", "z^3 - x", "x^4 - y*z + 1"];
        assert_eq!(gb(&gf(101), "xyz", &Order::Lex, &i), ["x + 19", "y + 48", "z + 68"]);
        assert_eq!(gb(&gf(103), "xyz", &Order::Lex, &i), ["x + 39", "y + 8", "z + 85"]);
        assert_eq!(gb(&gf(27173681), "xyz", &Order::Lex, &i), ["x + 26637654", "y + 3186055", "z + 10380032"]);
        assert_eq!(gb(&gf(3), "xyz", &Order::Lex, &i), ["1"]);
        assert_eq!(gb(&Ctx::rationals(), "xyz", &Order::Lex, &i), ["1"]);
        let j = ["x^2 - 1", "y^2 - 1", "2*x*y - z"];
        assert_eq!(gb(&gf(2), "xyz", &Order::Lex, &j), ["x^2 + 1", "y^2 + 1", "z"]);
        assert_eq!(gb(&gf(3), "xyz", &Order::Lex, &j), ["x + y*z", "y^2 + 2", "z^2 + 2"]);
    }

    /// Check that `g` is the reduced Gröbner basis in `order` of the ideal
    /// generated by `gens`, sorted as Magma sorts it.
    fn check_reduced<F: Field>(field: &F, ring: &Ring, gens: &[Poly<F::E>], g: &[Poly<F::E>]) {
        let n = ring.n;
        let masks: Vec<u64> = g.iter().map(|p| poly::mask(p.lm(n))).collect();
        let all: Vec<usize> = (0..g.len()).collect();
        let nf = |f: &Poly<F::E>| poly::reduce(field, ring, f.clone(), 0, g, &masks, &all);
        for w in g.windows(2) {
            assert_eq!(ring.cmp(w[0].lm(n), w[1].lm(n)), std::cmp::Ordering::Greater);
        }
        for (k, p) in g.iter().enumerate() {
            assert!(field.is_one(p.lc()));
            for i in 0..p.len() {
                assert!((0..p.len()).skip(1).all(|j| ring.cmp(p.exp(j - 1, n), p.exp(j, n)).is_gt()));
                assert!(g.iter().enumerate().all(|(j, q)| j == k || !poly::divides(q.lm(n), p.exp(i, n))), "not reduced");
            }
            for q in &g[k + 1..] {
                let l = poly::lcm(p.lm(n), q.lm(n));
                let s = poly::sub_mul(field, ring, &p.shift(&poly::quotient(&l, p.lm(n)), n), 1, &field.one(), &poly::quotient(&l, q.lm(n)), q, 1);
                assert!(nf(&s).is_zero(), "an S-polynomial does not reduce to zero");
            }
        }
        assert!(gens.iter().all(|f| nf(f).is_zero()), "a generator is not in the ideal of the basis");
    }

    /// The Gröbner basis of `gens` in `order`, checked as above and against
    /// the one in `other`: each reduces the other to zero.
    fn checked<F: Field>(field: &F, n: usize, order: &Order, other: &Order, gens: &[Terms]) -> Vec<Poly<F::E>> {
        let (ring, ring2) = (Ring { n, order: order.clone() }, Ring { n, order: other.clone() });
        let polys = |r: &Ring| gens.iter().map(|t| import(field, r, t).unwrap()).collect::<Vec<_>>();
        let (g, g2) = (buchberger::groebner(field, &ring, polys(&ring), None), buchberger::groebner(field, &ring2, polys(&ring2), None));
        check_reduced(field, &ring, &polys(&ring), &g);
        check_reduced(field, &ring2, &polys(&ring2), &g2);
        let back = |p: &Poly<F::E>, r: &Ring| import(field, r, &export(field, &ring2, p)).unwrap();
        check_reduced(field, &ring, &g2.iter().map(|p| back(p, &ring)).collect::<Vec<_>>(), &g);
        g
    }

    #[test]
    fn handbook_graded_ideal_over_q() {
        // The handbook prints this basis in lex order, the default before
        // V2.15; the ring's order is now grevlexw with its weights.
        let q = Ctx::rationals();
        let l = ["a*b - c^2*d^3", "b*c*d + c^3", "c^2*d - d^5", "a*d - b*c"];
        let g = [
            "a*b - d^7", "a*c^3 + d^10", "a*d - b*c", "b^2*c - d^8", "b*c^3 + d^9", "b*c*d + c^3", "b*d^5 + c^4", "c^5 - d^10", "c^2*d - d^5", "c*d^7 - d^9",
        ];
        assert_eq!(gb(&q, "abcd", &Order::Lex, &l), g);
        let gens: Vec<Terms> = l.iter().map(|s| parse(&q, "abcd", s)).collect();
        let w = checked(&field::GrField::new(&q), 4, &Order::GRevLexW(vec![4, 3, 2, 1]), &Order::Lex, &gens);
        assert_eq!(w.len(), 10);
    }

    /// The cyclic-n system.
    pub fn cyclic(ctx: &Rc<Ctx>, n: usize) -> Vec<Terms> {
        let one = || Elem::one(ctx).unwrap();
        let mut sys: Vec<Terms> = (1..n)
            .map(|k| {
                (0..n)
                    .map(|i| {
                        let mut e = vec![0u64; n];
                        (0..k).for_each(|j| e[(i + j) % n] += 1);
                        (one(), e)
                    })
                    .collect()
            })
            .collect();
        sys.push(vec![(one(), vec![1; n]), (Elem::from_i64(ctx, -1).unwrap(), vec![0; n])]);
        sys
    }

    /// The katsura-n system, in n + 1 variables.
    pub fn katsura(ctx: &Rc<Ctx>, n: usize) -> Vec<Terms> {
        let c = |k: i64| Elem::from_i64(ctx, k).unwrap();
        let var = |i: usize| (0..=n).map(|j| (i == j) as u64).collect::<Vec<u64>>();
        let mut sys: Vec<Terms> = (0..n)
            .map(|m| {
                let mut t = Terms::new();
                for l in -(n as i64)..=n as i64 {
                    let (a, b) = (l.unsigned_abs() as usize, (m as i64 - l).unsigned_abs() as usize);
                    if a <= n && b <= n {
                        t.push((c(1), var(a).iter().zip(var(b)).map(|(x, y)| x + y).collect()));
                    }
                }
                t.push((c(-1), var(m)));
                t
            })
            .collect();
        let mut lin: Terms = (1..=n).map(|l| (c(2), var(l))).collect();
        lin.push((c(1), var(0)));
        lin.push((c(-1), vec![0; n + 1]));
        sys.push(lin);
        sys
    }

    #[test]
    #[ignore]
    fn timings() {
        let p = gf(32003);
        let big = std::env::var("GB_BIG").is_ok();
        let mut systems = vec![("cyclic-5", cyclic(&p, 5)), ("cyclic-6", cyclic(&p, 6)), ("katsura-5", katsura(&p, 5)), ("katsura-6", katsura(&p, 6))];
        if big {
            systems.extend([("cyclic-7", cyclic(&p, 7)), ("katsura-7", katsura(&p, 7)), ("katsura-8", katsura(&p, 8))]);
        }
        for (name, sys) in systems {
            let n = sys[0][0].1.len();
            let t = std::time::Instant::now();
            let g = groebner(&p, n, &Order::GRevLex, &sys).unwrap();
            println!("{name}: {} polynomials in {:.3} s", g.len(), t.elapsed().as_secs_f64());
        }
        let q = Ctx::rationals();
        for (name, sys) in [("cyclic-5/Q", cyclic(&q, 5)), ("katsura-4/Q", katsura(&q, 4))] {
            let n = sys[0][0].1.len();
            let t = std::time::Instant::now();
            let g = groebner(&q, n, &Order::GRevLex, &sys).unwrap();
            println!("{name}: {} polynomials in {:.3} s", g.len(), t.elapsed().as_secs_f64());
        }
    }

    fn random_system(ctx: &Rc<Ctx>, s: &mut u64, n: usize, count: usize, terms: usize, deg: u64) -> Vec<Terms> {
        let mut next = || {
            *s ^= *s << 13;
            *s ^= *s >> 7;
            *s ^= *s << 17;
            *s
        };
        (0..count)
            .map(|_| {
                (0..terms)
                    .map(|_| {
                        let mut e = vec![0u64; n];
                        (0..next() % (deg + 1)).for_each(|_| e[(next() % n as u64) as usize] += 1);
                        (Elem::from_i64(ctx, (next() % 201) as i64 - 100).unwrap(), e)
                    })
                    .collect()
            })
            .collect()
    }

    #[test]
    fn random_ideals_give_reduced_bases_in_every_order() {
        let orders = [
            Order::Lex,
            Order::GLex,
            Order::GRevLex,
            Order::GRevLexW(vec![3, 1, 2]),
            Order::ElimK(1),
            Order::Elim(vec![2], vec![1, 0]),
            Order::Univ(1),
            Order::Weight(Weights::new([[1, 1, 1], [0, 0, 1], [0, 1, 0]].iter().map(|r| r.iter().map(|&x| Integer::from_i64(x)).collect()).collect())),
        ];
        let p = gf(32003);
        let (zp, grp) = (field::Zp::new(&p), field::GrField::new(&p));
        let grevlex = Ring { n: 3, order: Order::GRevLex };
        let mut s = 0x243f6a8885a308d3;
        let mut changed = 0;
        for round in 0..24 {
            let gens = random_system(&p, &mut s, 3, 2 + round % 3, 3, 3);
            let g0 = f4::groebner(&zp, &grevlex, gens.iter().map(|t| import(&zp, &grevlex, t).unwrap()).collect(), &[1; 3], None);
            for o in &orders {
                let g = checked(&zp, 3, o, &Order::GRevLex, &gens);
                let ring = Ring { n: 3, order: o.clone() };
                // F4 and the generic field compute the same basis.
                let shown = |b: &[Poly<u64>]| b.iter().map(|p| show("xyz", &export(&zp, &ring, p))).collect::<Vec<_>>();
                let f4 = f4::groebner(&zp, &ring, gens.iter().map(|t| import(&zp, &ring, t).unwrap()).collect(), &[1; 3], None);
                assert_eq!(shown(&g), shown(&f4));
                let h = groebner_in(&grp, &ring, &gens, None).unwrap();
                assert_eq!(shown(&g), shows("xyz", &h));
                // So does the change of order when the ideal is zero-dimensional,
                // in words or with the field's elements.
                if let Some(h) = fglm::fglm(&zp, &grevlex, &g0, &ring) {
                    assert_eq!(shown(&g), shown(&h));
                    assert_eq!(shown(&h), shown(&fglm::fglm_field(&zp, &grevlex, &g0, &ring).unwrap()));
                    let g1 = imports(&grp, &grevlex, &exports(&zp, &grevlex, &g0)).unwrap();
                    assert_eq!(shown(&h), shows("xyz", &exports(&grp, &ring, &fglm::fglm_field(&grp, &grevlex, &g1, &ring).unwrap())));
                    changed += 1;
                }
            }
        }
        assert!(changed >= 64, "{changed} changes of order");
        let q = Ctx::rationals();
        let (grq, lex) = (field::GrField::new(&q), Ring { n: 3, order: Order::Lex });
        let mut zero_dimensional = 0;
        for round in 0..8 {
            let gens = random_system(&q, &mut s, 3, 2 + round % 2, 3, 2);
            let g = checked(&grq, 3, &Order::GRevLex, &Order::Lex, &gens);
            if let Some(h) = fglm::fglm_field(&grq, &grevlex, &g, &lex) {
                assert_eq!(shows("xyz", &exports(&grq, &lex, &h)), shows("xyz", &groebner_in(&grq, &lex, &gens, None).unwrap()));
                zero_dimensional += 1;
            }
        }
        assert!(zero_dimensional >= 3, "{zero_dimensional} zero-dimensional ideals");
    }

    #[test]
    fn change_of_order_for_zero_dimensional_ideals() {
        let mut s = 0x13198a2e03707344;
        let mut sizes = Vec::new();
        for round in 0..16 {
            // Also a prime near 2^31, where few products fit a word, and one
            // beyond, where the vectors are of the field's elements.
            let p = gf(match round % 4 {
                1 => (1 << 61) - 1,
                3 => (1 << 31) - 1,
                _ => 32003,
            });
            let zp = field::Zp::new(&p);
            let words = zp.modulus() < 1 << 31;
            let n = 2 + round % 3;
            let gens = random_system(&p, &mut s, n, n, 3 + round % 2, 2 + round as u64 % 3);
            let (grevlex, lex, elim) = (Ring { n, order: Order::GRevLex }, Ring { n, order: Order::Lex }, Ring { n, order: Order::ElimK(1) });
            let polys = imports(&zp, &grevlex, &gens).unwrap();
            let g0 = if words { f4::groebner(&zp, &grevlex, polys, &vec![1; n], None) } else { buchberger::groebner(&zp, &grevlex, polys, None) };
            let masks: Vec<u64> = g0.iter().map(|p| poly::mask(p.lm(n))).collect();
            let all: Vec<usize> = (0..g0.len()).collect();
            for ring in [&lex, &elim] {
                let polys: Vec<Poly<u64>> = gens.iter().map(|t| import(&zp, ring, t).unwrap()).collect();
                let h = if words { fglm::fglm(&zp, &grevlex, &g0, ring) } else { fglm::fglm_field(&zp, &grevlex, &g0, ring) };
                let Some(h) = h else { continue };
                // A reduced Gröbner basis whose ideal has the generators and is
                // in theirs.
                check_reduced(&zp, ring, &polys, &h);
                assert!(basis::is_groebner(&zp, ring, h.clone()));
                for f in &h {
                    let f = import(&zp, &grevlex, &export(&zp, ring, f)).unwrap();
                    assert!(poly::reduce(&zp, &grevlex, f, 0, &g0, &masks, &all).is_zero());
                }
            }
            sizes.push(g0.len());
        }
        assert!(sizes.iter().filter(|&&k| k > 1).count() >= 8);
        // Katsura-3 in lex, through grevlex.
        let p = gf(32003);
        let zp = field::Zp::new(&p);
        let k = katsura(&p, 3);
        let ring = Ring { n: 4, order: Order::Lex };
        let g = groebner(&p, 4, &Order::Lex, &k).unwrap();
        check_reduced(&zp, &ring, &imports(&zp, &ring, &k).unwrap(), &imports(&zp, &ring, &g).unwrap());
        assert_eq!(shows("abcd", &g), shows("abcd", &groebner_in(&zp, &ring, &k, None).unwrap()));
        assert_eq!(g.len(), 4);
        // And over the rationals.
        let q = Ctx::rationals();
        let k = katsura(&q, 3);
        let g = groebner(&q, 4, &Order::Lex, &k).unwrap();
        assert_eq!(shows("abcd", &g), shows("abcd", &groebner_in(&field::GrField::new(&q), &ring, &k, None).unwrap()));
    }

    fn shows(vars: &str, ts: &[Terms]) -> Vec<String> {
        ts.iter().map(|t| show(vars, t)).collect()
    }

    #[test]
    fn modular_bases_over_the_rationals() {
        // The modular method gives the bases computed over the rationals, in
        // graded orders and others, for ideals of dimension zero or more.
        let q = Ctx::rationals();
        let orders = [Order::Lex, Order::GLex, Order::GRevLex, Order::ElimK(1), Order::Univ(1), Order::GRevLexW(vec![1, 2, 3])];
        let rational = Strategy { rational: true };
        let mut s = 0x9e3779b97f4a7c15;
        for round in 0..12 {
            let mut gens = random_system(&q, &mut s, 3, 2 + round % 2, 3, 2);
            for (i, g) in gens.iter_mut().enumerate() {
                let d = Elem::from_i64(&q, 3 * (i + round) as i64 + 2).unwrap();
                g.iter_mut().for_each(|(c, _)| *c = c.div(&d).unwrap());
            }
            for o in &orders {
                let m = groebner(&q, 3, o, &gens).unwrap();
                assert_eq!(shows("xyz", &m), shows("xyz", &groebner_with(&q, 3, o, &gens, rational).unwrap()), "{o:?}");
            }
        }
        // Primes dividing a leading coefficient or a denominator are passed
        // over, and so is the first prime here, whose basis has other leading
        // monomials than the others.
        for gens in [["2147483647*x - 1", "y^2 - 1/2147483629"], ["x*y - 2147483647", "x^2 - 1"]] {
            let gens: Vec<Terms> = gens.iter().map(|g| parse(&q, "xy", g)).collect();
            for o in [Order::Lex, Order::GRevLex] {
                assert_eq!(shows("xy", &groebner(&q, 2, &o, &gens).unwrap()), shows("xy", &groebner_with(&q, 2, &o, &gens, rational).unwrap()));
            }
        }
        let gens = [parse(&q, "xy", "x*y - 2147483647"), parse(&q, "xy", "x^2 - 1")];
        assert_eq!(shows("xy", &groebner(&q, 2, &Order::Lex, &gens).unwrap()), ["x - 1/2147483647*y", "y^2 - 4611686014132420609"]);
        // Katsura-5 in lex, whose coefficients take a few hundred primes.
        let k = katsura(&q, 5);
        let g = groebner(&q, 6, &Order::Lex, &k).unwrap();
        assert_eq!(shows("abcdef", &g), shows("abcdef", &groebner_with(&q, 6, &Order::Lex, &k, rational).unwrap()));
    }

    #[test]
    fn truncated_bases() {
        // The handbook's example of degree-d bases, as Magma 2.22 computes
        // it in the graded ring and then in the ungraded one.
        let q = Ctx::rationals();
        let l = ["a*b - c^2*d^3", "b*c*d + c^3", "c^2*d - d^5", "a*d - b*c"];
        let gens: Vec<Terms> = l.iter().map(|s| parse(&q, "abcd", s)).collect();
        let t = |order: &Order, weights: &[u64], d: i128| shows("abcd", &truncated_groebner(&q, 4, order, &gens, weights, d).unwrap());
        let (w, graded) = (Order::GRevLexW(vec![4, 3, 2, 1]), [4, 3, 2, 1]);
        assert_eq!((1..=10).map(|d| t(&w, &graded, d).len()).collect::<Vec<_>>(), [4, 4, 4, 4, 4, 4, 5, 6, 9, 9]);
        assert_eq!(t(&w, &graded, 5), ["a*b - d^7", "c^3 + a*d^2", "b*c - a*d", "c^2*d - d^5"]);
        assert_eq!(t(&w, &graded, 8), ["a*c*d^2 - b*d^5", "a*b - d^7", "a*d^3 + c*d^5", "c^3 + a*d^2", "b*c - a*d", "c^2*d - d^5"]);
        assert_eq!(t(&w, &graded, 11), shows("abcd", &groebner(&q, 4, &w, &gens).unwrap()));
        let g = Order::GRevLex;
        assert_eq!((1..=10).map(|d| t(&g, &[1; 4], d).len()).collect::<Vec<_>>(), [4, 4, 4, 5, 6, 12, 11, 11, 11, 11]);
        let d6 = [
            "a*c*d^4 - a*b^2",
            "a^2*b^3 + a^4*d",
            "a^2*b^2*d - a^3*b",
            "a^3*d^2 + a^2*b^2",
            "a^2*d^3 + a^2*b",
            "c^2*d^3 - a*b",
            "d^5 - c^2*d",
            "a^2*c*d + a^2*b",
            "a*c^2*d + a^2*d",
            "a*b*d^2 - a^2*d",
            "c^3 + a*d^2",
            "b*c - a*d",
        ];
        assert_eq!(t(&g, &[1; 4], 6), d6);
        // A pair counts by the degree of its lcm, even where its sugar is
        // larger, and what it adds is kept whatever its degree.
        let p = gf(7);
        let gens: Vec<Terms> = ["x*y - y^4", "x^2 - y"].iter().map(|s| parse(&p, "xy", s)).collect();
        let t = |d: i128| shows("xy", &truncated_groebner(&p, 2, &Order::Lex, &gens, &[1, 1], d).unwrap());
        assert_eq!(t(2), ["x^2 + 6*y", "x*y + 6*y^4"]);
        assert_eq!(t(3), ["x^2 + 6*y", "x*y + 6*y^4", "y^7 + 6*y^2"]);
        assert_eq!(t(-1), ["x^2 + 6*y", "x*y + 6*y^4"]);
    }

    /// `NormalForm(f, S)` with its coordinates, over the field `ctx` in lex.
    fn division(ctx: &Rc<Ctx>, vars: &str, f: &str, s: &[&str]) -> (String, Vec<String>) {
        let s: Vec<Terms> = s.iter().map(|g| parse(ctx, vars, g)).collect();
        let (r, q) = divide(ctx, vars.len(), &Order::Lex, &parse(ctx, vars, f), &s).unwrap();
        (show(vars, &r), shows(vars, &q))
    }

    #[test]
    fn division_as_in_magma() {
        let q = Ctx::rationals();
        assert_eq!(division(&q, "xyz", "x^3*y", &["y^2 - x", "x*y - 1"]), ("y^7".into(), vec!["-x^2*y - x*y^3 - y^5".into(), "0".into()]));
        let (r, c) = division(&q, "xyz", "2*x^3*y + 3*y^3", &["3*x*y - 1", "2*y^2 - x"]);
        assert_eq!((r.as_str(), c), ("3*y^3 + 4/9*y", vec!["2/3*x^2 + 4/9*y".to_string(), "-2/3*x".to_string()]));
        let (r, c) = division(&q, "xyz", "x^2 + y", &["x - 1", "0", "x"]);
        assert_eq!((r.as_str(), c), ("y + 1", vec!["x + 1".to_string(), "0".to_string(), "0".to_string()]));
        let (r, c) = division(&q, "xyz", "x*y*z - 1", &["x*y - z", "0", "x*z - y"]);
        assert_eq!((r.as_str(), c), ("z^2 - 1", vec!["z".to_string(), "0".to_string(), "0".to_string()]));
        let (r, c) = division(&gf(7), "st", "s^3 + t", &["2*s - t", "t^2 - 1"]);
        assert_eq!((r.as_str(), c), ("2*t", vec!["4*s^2 + 2*s*t + t^2".to_string(), "t".to_string()]));
        // The divisors are tried in the order given.
        let nf = |s: &[&str]| {
            let s: Vec<Terms> = s.iter().map(|g| parse(&q, "xy", g)).collect();
            let fs: Vec<Terms> = ["x^2", "x*y + y^3"].iter().map(|f| parse(&q, "xy", f)).collect();
            shows("xy", &normal_forms(&q, 2, &Order::Lex, &fs, &s).unwrap())
        };
        assert_eq!(nf(&["x*y - 1", "y^2 - x"]), ["y", "y^3 + 1"]);
        assert_eq!(nf(&["y^2 - x", "x*y - 1"]), ["y^4", "2*y^3"]);
        assert_eq!(nf(&[]), ["x^2", "x*y + y^3"]);
    }

    fn reduced(f: fn(&Rc<Ctx>, usize, &Order, &[Terms]) -> Result<Vec<Terms>, Error>, s: &[&str]) -> Vec<String> {
        let q = Ctx::rationals();
        let s: Vec<Terms> = s.iter().map(|g| parse(&q, "xyz", g)).collect();
        shows("xyz", &f(&q, 3, &Order::Lex, &s).unwrap())
    }

    #[test]
    fn interreduction_as_in_magma() {
        let r = |s: &[&str]| reduced(interreduce, s);
        assert_eq!(r(&["x*y - z", "y - z", "x - z"]), ["x - z", "y - z", "z^2 - z"]);
        assert_eq!(r(&["y^2 - x", "x*y - z^3", "y - z"]), ["x - z^2", "y - z"]);
        assert_eq!(r(&["2*x^2 - y", "4*x^2*y - z", "3*x*z"]), ["x^2 - 1/2*y", "x*z", "y^2 - 1/2*z"]);
        assert_eq!(r(&["x*y - z^2", "x - y", "y^2 + z^3"]), ["x - y", "y^2 - z^2", "z^3 + z^2"]);
        assert_eq!(r(&["0", "x", "2*x"]), ["x"]);
        assert!(r(&[]).is_empty());
        // Whatever the order of the input, the least leading monomials
        // reduce first.
        for s in [["x*y - z", "x*z - y", "x*y*z - 1"], ["x*y*z - 1", "x*z - y", "x*y - z"]] {
            assert_eq!(r(&s), ["x*y - z", "x*z - y", "y^2 - 1"]);
        }
        for s in [["x*y*z + x", "x*y - z", "x*z - y"], ["x*z - y", "x*y - z", "x*y*z + x"]] {
            assert_eq!(r(&s), ["x + y^2", "y^3 + z", "y^2*z + y"]);
        }
        assert_eq!(r(&["x*y^2 - 1", "x*y - z", "x*y^2*z - y"]), ["x*z - z", "y - z", "z^2 - 1"]);
        assert_eq!(r(&["x^2*y^2 - 1", "x*y^2 - z", "x^2*y - z"]), ["x^2*y - z", "x*y^2 - z", "x*z - 1"]);
        assert_eq!(r(&["x*y + z^2", "x*y + z", "x*z"]), ["x*y + z", "x*z", "z^2 - z"]);
        assert_eq!(r(&["x*y + y", "x*y + z", "y*z - 1"]), ["x*z + z", "y - z", "z^2 - 1"]);
    }

    #[test]
    fn basis_reduction_as_in_magma() {
        let r = |s: &[&str]| reduced(reduce_basis, s);
        assert_eq!(r(&["x^2 - y", "x^2*y - z", "x*z", "2*x^2 - 2*y"]), ["x^2 - y", "x*z"]);
        assert_eq!(r(&["2*x - 2", "x - 1", "x^2 - 1"]), ["x - 1"]);
        assert_eq!(r(&["x*y*z - 1", "x*z - y", "x*y - z"]), ["x*y - z", "x*z - y"]);
        // Of equal leading monomials, the least polynomial stays.
        for (a, b, kept) in [
            ("x*y - z^2", "2*x*y - z", "x*y - z^2"),
            ("2*x*y - z", "3*x*y - z", "x*y - 1/2*z"),
            ("x*y - 2*z", "x*y - 3*z", "x*y - 3*z"),
            ("x*y - 3*z", "x*y + 2*z", "x*y - 3*z"),
            ("x*y", "x*y + z", "x*y"),
        ] {
            assert_eq!(r(&[a, b]), [kept]);
            assert_eq!(r(&[b, a]), [kept]);
        }
    }

    #[test]
    fn groebner_test() {
        let q = Ctx::rationals();
        let is = |s: &[&str]| is_groebner(&q, 3, &Order::Lex, &s.iter().map(|g| parse(&q, "xyz", g)).collect::<Vec<_>>()).unwrap();
        assert!(!is(&["x^2 - y", "x*y - 1"]));
        assert!(is(&["x - y^2", "y^3 - 1"]));
        assert!(is(&["x - y^2", "y^3 - 1", "x*y - 1"]));
        assert!(is(&[]) && is(&["0"]) && is(&["x", "0"]) && is(&["2*x - 1"]));
        assert!(!is(&["x^2 + y", "x*y - 1"]));
    }

    #[test]
    fn trivial_ideals() {
        let q = Ctx::rationals();
        assert!(gb(&q, "xy", &Order::Lex, &[]).is_empty());
        assert!(gb(&q, "xy", &Order::Lex, &["0"]).is_empty());
        assert_eq!(gb(&q, "xy", &Order::GRevLex, &["x*y + 1", "x"]), ["1"]);
        assert_eq!(gb(&q, "xy", &Order::GRevLex, &["2*x*y - 4", "0", "3*x*y - 6"]), ["x*y - 2"]);
        assert_eq!(groebner(&Ctx::integers(), 2, &Order::Lex, &[]).err(), Some(Error::Unsupported));
    }
}
