//! Structure operations: related structures, numerical invariants,
//! defining polynomials and roots.

use super::*;

pub(super) fn degree_ff(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let f = field_arg(a, 0)?;
    intv(Integer::from_u64(degree(&f)))
}

pub(super) fn degree_over(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let (f, e) = (field_arg(a, 0)?, field_arg(a, 1)?);
    sub_image(&e, &f, NOT_SUB_OF)?;
    intv(Integer::from_u64(degree(&f) / degree(&e)))
}

pub(super) fn is_conway(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let f = field_arg(a, 0)?;
    boolv(ff(&f).1.conway)
}

pub(super) fn is_default(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let f = field_arg(a, 0)?;
    boolv(ff(&f).1.default)
}

pub(super) fn defining_polynomial(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let f = field_arg(a, 0)?;
    let fd = ff(&f).1;
    if let Some(g) = &fd.ground {
        let (k, poly) = (g.field.clone(), g.poly.clone());
        return one(poly_value(it, &k, &poly)?);
    }
    let p = fd.p.clone();
    // A prime field is generated by 1.
    let modulus = if fd.degree == 1 { vec![&p - &Integer::one(), Integer::one()] } else { fd.modulus.clone() };
    one(int_poly_value(it, &p, &modulus)?)
}

pub(super) fn defining_polynomial_over(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let (f, e) = (field_arg(a, 0)?, field_arg(a, 1)?);
    sub_image(&e, &f, NOT_SUB_OF)?;
    let g = gen_over(it, &f, &e)?;
    let mp = finite::min_poly(&g, &f, &e).ok_or_else(bad)?;
    one(poly_value(it, &e, &mp)?)
}

/// The map from an abelian group onto the additive or multiplicative group
/// of a field: `A.i` to the (i-1)-th power of `Generator(F, GF(p))`, or
/// `M.1` to the primitive element.
struct GroupMap {
    field: Rc<Struct>,
    base: Elem,
    additive: bool,
}

fn group_coords(m: &MapObj, x: &Value) -> RResult<Box<[Integer]>> {
    match (x, &m.domain) {
        (Value::AbElt(e), Value::Struct(st)) if Rc::ptr_eq(&e.group, st) => Ok(e.coords.clone()),
        _ => Err(RuntimeError::runtime("Application of map failed").in_context("map application")),
    }
}

impl NativeMap for GroupMap {
    fn apply(&self, _it: &mut Interp, m: &MapObj, x: &Value) -> RResult<Value> {
        let c = group_coords(m, x)?;
        let ctx = ff(&self.field).0.ctx.clone();
        let y = if self.additive {
            let mut acc = Elem::zero(&ctx);
            for ci in c.iter().rev() {
                acc = acc.mul(&self.base)?.add(&Elem::from_integer(&ctx, ci)?)?;
            }
            acc
        } else {
            self.base.pow(&c[0])?
        };
        Ok(make_elt(&self.field, y))
    }

    fn preimage(&self, it: &mut Interp, m: &MapObj, y: &Value) -> RResult<Value> {
        let fail = || RuntimeError::runtime("Application of map failed").in_context("@@");
        let y = it.to_structure_elem(&Value::Struct(self.field.clone()), y, false)?.ok_or_else(fail)?;
        let Value::Struct(g) = &m.domain else { unreachable!() };
        let coords = if self.additive {
            let fp = prime_of(it, &self.field)?;
            let one_ = Elem::one(&ff(&fp).0.ctx)?;
            coords_over(&self.field, &y, &fp, &one_, &self.base).iter().map(|c| c.to_integer().unwrap_or_default()).collect()
        } else {
            if is_zero(&y) {
                return Err(RuntimeError::runtime("Can not take log of zero element").in_context("@@"));
            }
            vec![log_base(it, &self.field, &self.base, &y)?.ok_or_else(fail)?]
        };
        Ok(crate::abgroups::elt(g, coords))
    }

    fn image(&self, _it: &mut Interp, _m: &MapObj) -> Option<RResult<Value>> {
        Some(Ok(Value::Struct(self.field.clone())))
    }
}

/// A group with its map; a statement printing the call shows the group.
fn with_map(a: &CallArgs, group: Rc<Struct>, map: Value) -> RResult<Vals> {
    if a.nresults < 2 { one(Value::Struct(group)) } else { Ok(vals![Value::Struct(group), map]) }
}

fn group_map(group: &Rc<Struct>, f: &Rc<Struct>, imp: GroupMap) -> Value {
    let (domain, codomain) = (Value::Struct(group.clone()), Value::Struct(f.clone()));
    Value::Map(Rc::new(MapObj { kind: MapKind::Map, domain, codomain, imp: MapImpl::Native(Rc::new(imp)) }))
}

pub(super) fn additive_group(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let f = field_arg(a, 0)?;
    let (p, n) = (ff(&f).1.p.clone(), degree(&f));
    let group = crate::abgroups::new_group(vec![p; n as usize]);
    let fp = prime_of(it, &f)?;
    let base = gen_over(it, &f, &fp)?;
    let map = group_map(&group, &f, GroupMap { field: f.clone(), base, additive: true });
    with_map(a, group, map)
}

pub(super) fn multiplicative_group(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let f = field_arg(a, 0)?;
    let q1 = &ff(&f).1.order() - &Integer::one();
    let group = crate::abgroups::new_group(vec![q1]);
    let base = it.ff_primitive(&f)?;
    let map = group_map(&group, &f, GroupMap { field: f.clone(), base, additive: false });
    with_map(a, group, map)
}

pub(super) fn root_of_unity(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let n = a.int(0)?.clone();
    let k = field_arg(a, 1)?;
    if n.sign() <= 0 {
        return Err(super::arg_ge(1, &n, 1));
    }
    if n.to_u64().is_none_or(|n| n >= 1 << 30) {
        return Err(RuntimeError::runtime(format!("Argument 1 ({n}) is too large")));
    }
    let q = ff(&k).1.order();
    if !n.gcd(&q).is_one() {
        return Err(RuntimeError::runtime(format!("Argument 1 ({n}) is not coprime to the size of argument 2")));
    }
    let m = crate::intrinsics::ints::modorder(&q.div_rem_euclid(&n).unwrap().1, &n).to_u64().filter(|&m| m < 1 << 20);
    let m = m.ok_or_else(|| RuntimeError::runtime("Extension degree is too large"))?;
    let m = m.max(1);
    let l = it.ff_ext_degree(&k, m)?;
    let pe = it.ff_primitive(&l)?;
    let e = (&ff(&l).1.order() - &Integer::one()).divexact(&n);
    one(make_elt(&l, pe.pow(&e)?))
}

// ----- roots ---------------------------------------------------------------------------

/// The roots of a non-constant polynomial in its coefficient field with
/// their multiplicities, in Magma's order.
fn poly_roots(f: &Elem) -> RResult<Vec<(Elem, u64)>> {
    let mut roots = match f.poly_roots() {
        Ok(rs) => rs,
        Err(_) => f.poly_factor()?.1.into_iter().filter(|(h, _)| h.poly_len() == 2).map(|(h, m)| (h.poly_coeff(0).neg().unwrap(), m)).collect(),
    };
    roots.sort_by(|x, y| elem_cmp(&x.0, &y.0));
    Ok(roots)
}

/// `RootsInSplittingField` and `FactorizationOverSplittingField`: the
/// roots in order, or the linear factors ordered by their constant terms.
fn over_splitting_field(it: &mut Interp, a: &mut CallArgs, factors: bool) -> RResult<Vals> {
    let (k, f) = ff_poly_arg(&a.args[0])?;
    if f.poly_len() == 0 {
        return Err(super::arg_not(1, "non-zero"));
    }
    let l = splitting_degree(&f)?;
    let s = it.ff_ext_degree(&k, l)?;
    let img = sub_image(&k, &s, "No embedding")?;
    let sctx = ff(&s).0.ctx.clone();
    let cs: Vec<Elem> = (0..f.poly_len()).map(|i| finite::embed_with(&f.poly_coeff(i), degree(&k), &img)).collect();
    let g = Elem::poly_from_coeffs(&Ctx::poly(&sctx), &cs)?;
    let mut roots = if g.poly_len() >= 2 { poly_roots(&g)? } else { Vec::new() };
    if factors {
        roots.iter_mut().for_each(|(r, _)| *r = r.neg().unwrap());
        roots.sort_by(|x, y| elem_cmp(&x.0, &y.0));
    }
    let mut out = Vec::with_capacity(roots.len());
    for (r, m) in roots {
        let x = if factors { poly_value(it, &s, &[r, Elem::one(&sctx)?])? } else { make_elt(&s, r) };
        out.push(Value::tuple(vec![x, Value::int(m as i64)]));
    }
    Ok(vals![Value::seq(None, out), Value::Struct(s)])
}

pub(super) fn roots_in_splitting_field(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    over_splitting_field(it, a, false)
}

pub(super) fn factorization_over_splitting_field(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    over_splitting_field(it, a, true)
}
