//! Ideals of univariate polynomial rings and quotient rings.
//!
//! An ideal of a univariate polynomial ring P over a field is a structure of
//! type RngUPol with its monic (or zero) generator (`StructKind::UPolIdeal`);
//! the ideal generated by a unit is P itself. The quotient P/(f) is a ring
//! of type RngUPolRes (`RingKind::UPolyRes`) whose elements are remainders
//! modulo f in the context of P, reduced here rather than by FLINT.

use std::rc::Rc;

use calyx_flint::Integer;
use calyx_flint::gr::{Ctx, Elem, GrResult, Truth};
use calyx_flint::upoly as fu;
use calyx_syntax::ast::BinOp;

use super::{base_of, pol, ring_arg};
use crate::error::{RResult, RuntimeError};
use crate::interp::{CallArgs, Interp};
use crate::intrinsics::{boolv, one};
use crate::rings::props::ring_props;
use crate::rings::{Elt, Ring, RingKind, make_elt, ring_of};
use crate::value::*;

/// The modulus of a quotient ring.
pub fn res_modulus(r: &Ring) -> &Elem {
    match &r.kind {
        RingKind::UPolyRes { modulus, .. } => modulus,
        _ => unreachable!("a polynomial quotient ring"),
    }
}

/// `x` reduced modulo the modulus `f` (monic, or over a field).
pub fn res_reduce(f: &Elem, x: Elem) -> GrResult<Elem> {
    if x.poly_len() < f.poly_len() {
        return Ok(x);
    }
    Ok(fu::divrem(&x, f)?.1)
}

/// The inverse of `x` modulo `f`: `None` if `x` is not a unit, an error
/// where Magma cannot decide (coefficient rings that are not fields).
fn res_inverse(f: &Elem, x: &Elem) -> RResult<Option<Elem>> {
    if !fu::over_field(f.ctx()) {
        if x.poly_len() == 1 && x.poly_coeff(0).is_invertible() == Truth::True {
            return Ok(Some(Elem::poly_from_coeffs(f.ctx(), &[x.poly_coeff(0).inv()?])?));
        }
        return Err(RuntimeError::runtime("Inverse/unit testing not available"));
    }
    if f.poly_len() == 1 {
        return Ok(Some(Elem::zero(f.ctx())));
    }
    let (d, s, _) = fu::xgcd(x, f)?;
    if d.poly_len() != 1 {
        return Ok(None);
    }
    Ok(Some(res_reduce(f, s)?))
}

/// `x^k` in a quotient ring (`k < 0` for units).
pub fn res_pow(f: &Elem, x: &Elem, k: &Integer) -> RResult<Elem> {
    let (x, k) = if k.sign() < 0 {
        match res_inverse(f, x).map_err(|e| e.in_context("^"))? {
            Some(y) => (y, -k),
            None => return Err(RuntimeError::runtime("Argument is not invertible").in_context("^")),
        }
    } else {
        (x.clone(), k.clone())
    };
    Ok(fu::powmod(&x, &k, f)?)
}

/// `x / y` in a quotient ring.
pub fn res_div(f: &Elem, x: &Elem, y: &Elem) -> RResult<Elem> {
    match res_inverse(f, y).map_err(|e| e.in_context("/"))? {
        Some(z) => Ok(res_reduce(f, x.mul(&z)?)?),
        None => Err(RuntimeError::runtime("Argument is not invertible").in_context("/")),
    }
}

/// The elements of a finite quotient ring, counting through the vectors of
/// coefficients (constant term fastest) with each coefficient running
/// through the coefficient ring in its order.
pub fn enumerate_res(it: &mut Interp, st: &Rc<Struct>, r: &Ring) -> RResult<Vec<Value>> {
    let RingKind::UPolyRes { base, modulus, .. } = &r.kind else { unreachable!() };
    let (base, d) = (base.clone(), modulus.poly_len() - 1);
    let q = ring_props(&base).and_then(|p| p.cardinality).ok_or_else(|| RuntimeError::runtime(crate::error::NOT_ITERABLE))?;
    let n = q.pow(d as u64).to_u64().filter(|&n| n <= 1 << 26).ok_or_else(|| RuntimeError::runtime("The ring is too large to enumerate"))?;
    let digits: Vec<Elem> = match &base {
        Value::Struct(bs) => it.enumerate_ring(bs)?.iter().map(|v| Ok(it.to_structure_elem(&base, v, false)?.expect("an element of the coefficient ring"))).collect::<RResult<_>>()?,
        _ => unreachable!("a finite coefficient ring"),
    };
    let mut idx = vec![0usize; d];
    let mut out = Vec::with_capacity(n as usize);
    for _ in 0..n {
        let cs: Vec<Elem> = idx.iter().map(|&i| digits[i].clone()).collect();
        out.push(make_elt(st, Elem::poly_from_coeffs(&r.ctx, &cs)?));
        for i in idx.iter_mut() {
            *i += 1;
            if *i < digits.len() {
                break;
            }
            *i = 0;
        }
    }
    Ok(out)
}

/// Whether the quotient by `f` is a domain (and so a field over a field):
/// `f` irreducible, where that can be decided.
pub fn res_is_domain(f: &Elem) -> bool {
    fu::can_factor(f.ctx()) && fu::is_irreducible(f).unwrap_or(false)
}

/// The generators of `ideal<P | ...>` or `quo<P | ...>` as polynomials:
/// elements coercing into P, sequences of them, and ideals of P.
fn poly_generators(it: &mut Interp, pst: &Rc<Struct>, right: &[Value], ctx: &str) -> RResult<Vec<Elem>> {
    let invalid = |i: usize| RuntimeError::runtime(format!("Rhs argument {} is invalid for this constructor", i + 1)).in_context(ctx);
    let mut out = Vec::new();
    for (i, v) in right.iter().enumerate() {
        if let Some(StructKind::UPolIdeal(g)) = v.as_struct() {
            if Rc::ptr_eq(&g.parent, pst) {
                out.push(g.x.clone());
                continue;
            }
            return Err(invalid(i));
        }
        let items: Vec<Value> = match v {
            Value::Seq(s) => s.elems.clone(),
            _ => vec![v.clone()],
        };
        for x in items {
            out.push(it.to_ring_elem(pst, &x, false)?.ok_or_else(|| invalid(i))?);
        }
    }
    Ok(out)
}

/// The monic gcd of polynomials over a field (0 for none).
fn gcd_all(ctx: &Rc<Ctx>, gs: &[Elem]) -> GrResult<Elem> {
    let mut g = Elem::zero(ctx);
    for x in gs {
        g = fu::gcd(&g, x)?;
    }
    if g.poly_len() > 0 { fu::make_monic(&g) } else { Ok(g) }
}

/// The ideal of the ring `pst` generated by `g` (monic or zero): the ring
/// itself for a unit.
fn poly_ideal(pst: &Rc<Struct>, g: Elem) -> Value {
    if g.poly_len() == 1 {
        return Value::Struct(pst.clone());
    }
    Value::structure(StructKind::UPolIdeal(Rc::new(Elt { parent: pst.clone(), x: g })))
}

/// A univariate polynomial ring, or an ideal of one: the ring and the
/// generator of the ideal (1 for the ring).
fn poly_ideal_parts(v: &Value) -> Option<(Rc<Struct>, Elem)> {
    match v.as_struct()? {
        StructKind::UPolIdeal(g) => Some((g.parent.clone(), g.x.clone())),
        StructKind::Ring(r) if matches!(r.kind, RingKind::UPoly { .. }) => {
            let Value::Struct(st) = v else { unreachable!() };
            Some((st.clone(), Elem::one(&r.ctx).ok()?))
        }
        _ => None,
    }
}

fn coercion_map(domain: Value, codomain: Value) -> Value {
    Value::Map(Rc::new(MapObj { kind: MapKind::Map, domain, codomain, imp: MapImpl::Coercion }))
}

/// `ideal<P | ...>` for a univariate polynomial ring P over a field.
pub fn ideal_constructor(it: &mut Interp, base: &Value, right: &[Value]) -> RResult<Option<Vec<Value>>> {
    let Some((pst, pr)) = ring_of(base).filter(|(_, r)| matches!(r.kind, RingKind::UPoly { .. })) else { return Ok(None) };
    let (pst, pctx) = (pst.clone(), pr.ctx.clone());
    if !fu::over_field(&pctx) {
        return Err(RuntimeError::runtime("Coefficient ring of LHS must be a field").in_context("ideal< ... >"));
    }
    let gs = poly_generators(it, &pst, right, "ideal< ... >")?;
    Ok(Some(vec![poly_ideal(&pst, gcd_all(&pctx, &gs)?)]))
}

/// `quo<P | ...>` for a univariate polynomial ring P: the quotient by the
/// ideal generated (P itself for the zero ideal) and the quotient map. Over
/// coefficient rings that are not fields there must be one monic generator.
pub fn quo_constructor(it: &mut Interp, base: &Value, right: &[Value]) -> RResult<Option<Vec<Value>>> {
    let Some((pst, pr)) = ring_of(base).filter(|(_, r)| matches!(r.kind, RingKind::UPoly { .. })) else { return Ok(None) };
    let (pst, pctx) = (pst.clone(), pr.ctx.clone());
    let gs = poly_generators(it, &pst, right, "quo< ... >")?;
    let g = if fu::over_field(&pctx) {
        gcd_all(&pctx, &gs)?
    } else {
        if gs.len() != 1 {
            return Err(RuntimeError::runtime("Arity must be 1 if coefficient ring is not a field").in_context("quo< ... >"));
        }
        if gs[0].poly_len() == 0 || fu::lead(&gs[0]).is_one() != Truth::True {
            return Err(RuntimeError::runtime("Polynomial must be monic").in_context("quo< ... >"));
        }
        gs[0].clone()
    };
    if g.poly_len() == 0 {
        return Ok(Some(vec![base.clone(), coercion_map(base.clone(), base.clone())]));
    }
    let q = it.upoly_res(&pst, g);
    Ok(Some(vec![q.clone(), coercion_map(base.clone(), q)]))
}

/// Operators on ideals of univariate polynomial rings (with at least one
/// proper ideal among the operands).
pub fn ideal_binop(it: &mut Interp, op: BinOp, a: &Value, b: &Value) -> RResult<Option<Value>> {
    let is_ideal = |v: &Value| matches!(v.as_struct(), Some(StructKind::UPolIdeal(_)));
    if !is_ideal(a) && !is_ideal(b) {
        return Ok(None);
    }
    let (Some((r, f)), Some((s, g))) = (poly_ideal_parts(a), poly_ideal_parts(b)) else { return Ok(None) };
    if !Rc::ptr_eq(&r, &s) {
        if matches!(op, BinOp::Eq | BinOp::Ne) {
            return Ok(Some(Value::Bool(op == BinOp::Ne)));
        }
        return Err(RuntimeError::runtime(format!("Arguments are not compatible\nArgument types given: {}, {}", it.type_name_ext(a), it.type_name_ext(b))).in_context(op.intrinsic_name()));
    }
    // I is contained in J when the generator of J divides that of I.
    let contained = |f: &Elem, g: &Elem| -> GrResult<bool> { Ok(if g.poly_len() == 0 { f.poly_len() == 0 } else { fu::divrem(f, g)?.1.poly_len() == 0 }) };
    let ctx = f.ctx().clone();
    Ok(Some(match op {
        BinOp::Add => poly_ideal(&r, gcd_all(&ctx, &[f, g])?),
        BinOp::Mul => poly_ideal(&r, f.mul(&g)?),
        BinOp::Meet => {
            let l = if f.poly_len() == 0 || g.poly_len() == 0 { Elem::zero(&ctx) } else { fu::divrem(&f.mul(&g)?, &fu::gcd(&f, &g)?)?.0 };
            poly_ideal(&r, if l.poly_len() > 0 { fu::make_monic(&l)? } else { l })
        }
        BinOp::Eq | BinOp::Ne => Value::Bool((f.equal(&g) == Truth::True) == (op == BinOp::Eq)),
        BinOp::Subset => Value::Bool(contained(&f, &g)?),
        BinOp::Notsubset => Value::Bool(!contained(&f, &g)?),
        _ => return Ok(None),
    }))
}

/// Whether `x` lies in the ideal generated by `g` of the ring `pst`: the
/// element of P if it does (`None` if x is not in P).
pub fn ideal_member(it: &mut Interp, pst: &Rc<Struct>, g: &Elem, x: &Value) -> RResult<Option<(Value, bool)>> {
    let Some(y) = it.to_ring_elem(pst, x, false)? else { return Ok(None) };
    let inside = if g.poly_len() == 0 { y.poly_len() == 0 } else { fu::divrem(&y, g)?.1.poly_len() == 0 };
    Ok(Some((make_elt(pst, y), inside)))
}

/// The text of an ideal: `Ideal of P generated by g`, or at the Magma
/// level `ideal<P | g>` (with the generator in the variable x, as Magma
/// prints it).
pub fn format_ideal(it: &mut Interp, g: &Elt, level: crate::print::Level) -> RResult<String> {
    use crate::print::Level;
    if level == Level::Magma {
        let p = it.format_flat(&g.parent_value(), Level::Magma)?;
        let gs = crate::rings::upoly_text(it, &base_of(g), &g.x, "x", Level::Default)?;
        return Ok(format!("ideal<{p} | {gs}>"));
    }
    let p = it.format_flat(&g.parent_value(), Level::Default)?;
    let gs = it.format_flat(&Value::Elt(Rc::new(Elt { parent: g.parent.clone(), x: g.x.clone() })), level)?;
    Ok(format!("Ideal of {p} generated by {gs}"))
}

pub(super) fn ideal_generators(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let Some((pst, g)) = poly_ideal_parts(&a.args[0]) else { return Err(RuntimeError::runtime("Bad argument types")) };
    one(Value::Set(Rc::new(SetEnum::new(Some(Value::Struct(pst.clone())), [make_elt(&pst, g)].into_iter().collect()))))
}

pub(super) fn ideal_is_prime(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let Some((_, g)) = poly_ideal_parts(&a.args[0]) else { return Err(RuntimeError::runtime("Bad argument types")) };
    boolv(g.poly_len() == 0 || (g.poly_len() > 1 && res_is_domain(&g)))
}

pub(super) fn ideal_is_maximal(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let Some((_, g)) = poly_ideal_parts(&a.args[0]) else { return Err(RuntimeError::runtime("Bad argument types")) };
    boolv(g.poly_len() > 1 && res_is_domain(&g))
}

pub(super) fn ideal_is_principal(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    boolv(poly_ideal_parts(&a.args[0]).is_some())
}

pub(super) fn modulus(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let (_, r) = ring_arg(a, 0);
    let RingKind::UPolyRes { preimage, modulus, .. } = &r.kind else { unreachable!() };
    one(make_elt(preimage, modulus.clone()))
}

pub(super) fn preimage_ring(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let (_, r) = ring_arg(a, 0);
    let RingKind::UPolyRes { preimage, .. } = &r.kind else { unreachable!() };
    one(Value::Struct(preimage.clone()))
}

pub(super) fn res_is_unit(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let f = pol(a, 0);
    boolv(res_inverse(res_modulus(f.ring()), &f.x)?.is_some())
}

/// The coefficient ring of a polynomial ring, ideal or quotient (or of the
/// parent of an element).
pub(super) fn coefficient_ring(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let r = match &a.args[0] {
        Value::Elt(e) => e.ring_rc(),
        _ => ring_arg(a, 0).1,
    };
    one(r.base().expect("a polynomial ring").clone())
}

pub(super) fn res_is_zero(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    boolv(pol(a, 0).x.poly_len() == 0)
}

pub(super) fn res_is_one(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    boolv(pol(a, 0).x.is_one() == Truth::True)
}

pub(super) fn res_is_minus_one(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    boolv(pol(a, 0).x.is_neg_one() == Truth::True)
}
